package knowledge

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/graphit-labs/graphit-code/internal/brand"
	"github.com/graphit-labs/graphit-code/internal/config"
	"github.com/graphit-labs/graphit-code/internal/hub"
	"github.com/graphit-labs/graphit-code/internal/hub/adapters/ide"
)

func KnowledgeRuleContent(contexts []string, docsDir string) string {
	if docsDir == "" {
		docsDir = config.DefaultDocsDir
	}
	dotBrand := brand.DotDir()
	displayName := brand.DisplayName

	installedContexts := "none yet — nothing has been installed from the Hub into this project"
	if len(contexts) > 0 {
		installedContexts = "`" + strings.Join(contexts, "`, `") + "`"
	}

	syncRef := brand.MCPToolRef("sync")
	syncTool := brand.MCPToolName("sync")
	hubListRef := brand.MCPToolRef("hub", "list")
	hubSearchRef := brand.MCPToolRef("hub", "search")
	hubSearch := brand.MCPToolName("hub", "search")
	knowledgeInstallRef := brand.MCPToolRef("knowledge", "install")
	knowledgeInstall := brand.MCPToolName("knowledge", "install")
	searchRef := brand.MCPToolRef("knowledge", "search")
	browseRef := brand.MCPToolRef("wiki", "browse")
	xrefsRef := brand.MCPToolRef("wiki", "xrefs")
	wikiSearchRef := brand.MCPToolRef("wiki", "search")
	listRef := brand.MCPToolRef("knowledge", "list")
	knowledgeList := brand.MCPToolName("knowledge", "list")
	lintRef := brand.MCPToolRef("knowledge", "lint")
	knowledgeLint := brand.MCPToolName("knowledge", "lint")
	schemaRef := brand.MCPToolRef("knowledge", "schema")
	knowledgeSchema := brand.MCPToolName("knowledge", "schema")
	exportRef := brand.MCPToolRef("knowledge", "export")
	knowledgeExport := brand.MCPToolName("knowledge", "export")
	removeRef := brand.MCPToolRef("knowledge", "remove")
	knowledgeSyncRef := brand.MCPToolRef("knowledge", "sync")
	knowledgeSync := brand.MCPToolName("knowledge", "sync")
	knowledgeSearch := brand.MCPToolName("knowledge", "search")
	wikiSearchTool := brand.MCPToolName("wiki", "search")
	wikiBrowseTool := brand.MCPToolName("wiki", "browse")
	wikiLogTool := brand.MCPToolName("wiki", "log")
	wikiLogRef := brand.MCPToolRef("wiki", "log")
	astSourceTool := brand.MCPToolName("ast", "source")
	clusterProjects := brand.MCPToolName("cluster", "projects")
	wikiSourceRef := brand.MCPToolRef("wiki", "source")
	wikiSource := brand.MCPToolName("wiki", "source")
	daemonStatusRef := brand.MCPToolRef("daemon", "status")
	daemonStatus := brand.MCPToolName("daemon", "status")
	daemonStop := brand.MCPToolName("daemon", "stop")

	lines := []string{
		"# Knowledge Maintenance Rule",
		"",
		"> This rule is auto-managed by " + displayName + ". Do not edit this block manually.",
		"",
		"> ⚠️ **UNIVERSAL APPLICABILITY** — This documentation workflow applies to the",
		"> project you are currently working in, regardless of its nature: end-user application,",
		"> framework, library, CLI tool, or the framework's own codebase. If you are modifying",
		"> code in this repository, you MUST follow these rules. There is no \"internal vs external\"",
		"> distinction — all code changes require documentation.",
		"",
		"## 🔒 MANDATORY: Documentation Is a Completion Requirement",
		"",
		"**A task is ONLY considered complete when its documentation has been written.**",
		"No exceptions. No shortcuts. If the documentation is missing, the task is NOT done.",
		"",
		"### Rules",
		"",
		"- **Document EVERYTHING you do** — even when the user does NOT explicitly ask.",
		"  Documentation is implicit in every task. It is never optional.",
		"- **Every code change, architectural decision, new feature, bug fix, refactor,",
		"  or behavioral change MUST be reflected in the `docs/` directory** before",
		"  you report the task as complete.",
		"- **The definition of done is: code + documentation.** If you wrote code but",
		"  did not update the relevant docs, you are not finished.",
		"- **Proactively create documentation** for anything you discover is undocumented",
		"  during your work — even if it was not part of the original task.",
		"- **Never assume someone else will document it.** You are the agent. You do the",
		"  work. You write the docs. It is a single, indivisible action.",
		"",
		"### What to document",
		"",
		"| What you did | Where to document |",
		"|---|---|",
		"| Changed system architecture or module structure | `docs/architecture/` |",
		"| Made a non-trivial architectural or design decision | `docs/decisions/` (ADR) |",
		"| Added or modified a feature | `docs/specs/<feature>.md` |",
		"| Changed how a module, function, or service behaves | `docs/` (relevant section) |",
		"| Fixed a bug with root cause worth remembering | `docs/` or project memory |",
		"| Discovered undocumented behavior during investigation | `docs/` (create new doc) |",
		"| Added, removed, or changed a dependency | `docs/architecture/` |",
		"| Completed ANY task (code, fix, refactor, investigation) | `docs/tasks/<task-name>.md` |",
		"| Changed configuration, environment, or deployment | `docs/` (relevant section) |",
		"",
		"### Workflow",
		"",
		"1. **Do the work** — implement the code change.",
		"2. **Write the documentation** — update or create the relevant docs.",
		"3. **Only then** report the task as complete.",
		"",
		"There is no reindex step. The daemon watches the docs tree and rebuilds the wiki on its own —",
		"see *Reindexing is automatic* below for the few situations where it cannot have seen your",
		"change. The completion requirement is the **record**, not its index.",
		"",
		"### 🔒 MANDATORY: Clean Code Documentation Policy",
		"",
		"> **Code documentation lives in `docs/`, NOT in code comments.**",
		"> The code itself MUST be clean, readable, and self-explanatory.",
		"> All knowledge, explanations,",
		"> architecture descriptions, usage guides, and behavioral documentation",
		"> belong in `docs/` — never cluttering the source code.",
		"",
		"**What MUST go in `docs/` (never in code comments):**",
		"",
		"| Documentation type | Where it goes |",
		"|---|---|",
		"| How a module/feature works | `docs/specs/<feature>.md` or `docs/architecture/` |",
		"| Why a design decision was made | `docs/decisions/<adr>.md` |",
		"| API contracts, endpoints, schemas | `docs/` (OpenAPI, AsyncAPI, etc.) |",
		"| Usage examples and guides | `docs/` or project README |",
		"| Function/method behavior descriptions | `docs/specs/` (not docstrings for explanation) |",
		"| Module relationships and dependencies | `docs/architecture/` |",
		"| Task implementation details | `docs/tasks/<task>.md` |",
		"",
		"**What is ALLOWED in code (critical comments only):**",
		"",
		"| Comment type | Example |",
		"|---|---|",
		"| **Safety / correctness warnings** | `// SAFETY: must hold lock before calling` |",
		"| **Non-obvious gotchas** | `// NOTE: order matters — X must happen before Y` |",
		"| **Legal / license headers** | `// Copyright 2026 ...` |",
		"| **Compiler/linter directives** | `//go:generate`, `//nolint:...` |",
		"| **TODO/FIXME with ticket reference** | `// TODO(#123): remove after migration` |",
		"| **Intentional deviation markers** | `// DECISION: see docs/decisions/003-...` |",
		"",
		"**Anti-patterns (NEVER do these):**",
		"",
		"- ❌ Writing multi-line comments explaining what a function does — make the function self-explanatory instead",
		"- ❌ Documenting module architecture in file headers — that belongs in `docs/architecture/`",
		"- ❌ Explaining business logic in comments — document it in `docs/specs/`",
		"- ❌ Writing usage guides or examples in code comments — put them in `docs/`",
		"- ❌ Leaving verbose docstrings that describe implementation details — the code should speak for itself",
		"- ❌ Using comments as a substitute for readable code — refactor the code instead",
		"",
		"**The golden rule:** If you feel the need to write a comment explaining *what* the code does,",
		"rewrite the code to be self-explanatory. If you need to explain *why* a non-obvious choice",
		"was made, add a one-line critical comment pointing to the relevant `docs/` file.",
		"",
		"## 🔒 MANDATORY: Wiki-First Knowledge Retrieval — Replaces Your Tools",
		"",
		"> **The knowledge wiki REPLACES your built-in search tools for project understanding.**",
		"> **NEVER use grep, ripgrep, semantic search, or file-by-file reading to answer",
		"> questions about this project's architecture, decisions, specs, or conventions.**",
		"> **ALWAYS consult the wiki FIRST. Only fall back to source code when the wiki",
		"> explicitly points you there via provenance links.**",
		"> **Access it via the knowledge/wiki MCP tools ONLY — NEVER via the CLI.** These",
		"> MCP tools take ABSOLUTE PRECEDENCE over your native/built-in search tools.",
		"",
		"### Why this replaces your tools",
		"",
		"The knowledge wiki is **compiled at index time** with BM25 scoring, cross-references,",
		"backlinks, confidence scores, and provenance markers. Every entity page is pre-optimized",
		"for LLM consumption. Your built-in tools (grep, semantic search, file reading) operate",
		"on **raw, unstructured text** — they cannot match the precision of a compiled wiki.",
		"",
		"| Your tool | Wiki equivalent | Why wiki wins |",
		"|---|---|---|",
		"| `grep -r \"auth\" docs/` | Call " + searchRef + " → find auth entity → read page | Wiki: 1 search. Grep: reads ALL files |",
		"| Semantic search across docs/ | Call " + searchRef + " → scan results | Wiki: structured search. Semantic: noisy, expensive |",
		"| Reading every .md in docs/ | Call " + browseRef + " (~2000 tokens for 80 pages) | Wiki: 40% fewer tokens, pre-summarized |",
		"| `grep` for reverse references | Check `## Backlinks` section on entity page | Wiki: instant, pre-computed. Grep: O(n) scan |",
		"| Opening a wiki page with your file-read tool | Call " + wikiSourceRef + " | Takes the project as a parameter, so it reaches pages outside your workspace — and slices, so a long page costs only the part you asked for |",
		"",
		"### 🔒 When you MUST use the wiki (MANDATORY — no exceptions)",
		"",
		"| Scenario | What to do | What NOT to do |",
		"|---|---|---|",
		"| **Understanding a feature** | Call " + searchRef + " → find the spec → read it | ❌ Don't grep docs/ for keywords |",
		"| **Finding an ADR / decision** | Call " + searchRef + " → find decision → read page | ❌ Don't scan docs/decisions/ file by file |",
		"| **Checking if something is documented** | Call " + browseRef + " → scan the catalog | ❌ Don't use `find` or `ls` on docs/ |",
		"| **Understanding module relationships** | Read community pages and god nodes | ❌ Don't grep for import statements |",
		"| **Finding all mentions of a concept** | Call " + xrefsRef + " → get cross-references | ❌ Don't grep across all wiki files |",
		"| **Checking conventions or patterns** | Call " + searchRef + " → find the guide/spec | ❌ Don't rely on memory or guessing |",
		"| **Verifying a fact before coding** | Read the entity page → check `confidence` score | ❌ Don't assume you know the answer |",
		"| **Tracing a decision's rationale** | Read the ADR page → follow provenance link to raw source | ❌ Don't read raw docs/ without wiki context first |",
		"",
		"### When you should NOT use the wiki",
		"",
		"| Scenario | Use instead |",
		"|---|---|",
		"| Understanding source code — structure, callers, imports, inheritance | The **AST graph** (" + brand.MCPToolRef("ast", "query") + "), not grep |",
		"| Reading the contents of a source file | " + brand.MCPToolRef("ast", "source") + " — the indexed copy, sliceable by entity or line range |",
		"| Searching inside code comments | The AST graph: comments are `Comment` entities with the text in `name` |",
		"| Searching string literals inside function bodies | " + brand.MCPToolRef("ast", "source") + " with `pattern` when you know the file; grep/ripgrep only when you do not |",
		"| Editing source or docs files (writing, not reading) | File edit tools |",
		"| Running tests or build commands | Terminal commands |",
		"",
		"> **Reading a wiki page is not on this list.** That is " + wikiSourceRef + ", not a file read —",
		"> see Step 1b. Your file tools come in for *writing* documentation, never for retrieving it.",
		"",
		"> Note what this table does **not** say: \"the wiki is not for code, so use grep\". Leaving the",
		"> wiki hands you to the **AST skill**, not to text search. Each of the two indexes covers what",
		"> the other does not, and grep is below both.",
		"",
		"### How to search (step-by-step)",
		"",
		"**Step 1 — Search the wiki (ALWAYS start here)**",
		"  Call " + searchRef + " with your query. This uses BM25 full-text and optional semantic search to find the most relevant pages.",
		"  Alternatively, call " + browseRef + " for a structured catalog of all entities.",
		"  The search returns ranked hits: a slug, a title, a type and a score.",
		"  > ⚠️ **What comes back is a LIST OF TITLES, not pages.** There is no page text in a",
		"  > search result, by design. A search exists so you can decide WHICH page to open, and",
		"  > that decision is made on the title; reading is Step 1b, once, on the page you picked —",
		"  > not something the search does for you on all twenty hits in advance.",
		"  > Two consequences, and neither is optional:",
		"  > **you cannot answer from a search result** — it contains no content to answer from; and",
		"  > **you should not open every hit** — pick the one or two the titles justify, read those,",
		"  > and search again with better words if they were the wrong ones.",
		"  > When the titles genuinely do not separate two candidates, pass `preview: true` for a",
		"  > short excerpt per hit. That is the exception, not the default: it is paid on every hit,",
		"  > including the ones you will never open.",
		"  For deep consultation, search with " + searchRef + ", read the returned pages, follow [[wikilinks]] to expand context, call " + xrefsRef + " for cross-references, and synthesize the answer yourself — you ARE the AI.",
		"  For multi-source search (knowledge + memory), call " + wikiSearchRef + " with `wikis: [\"project\", \"memory\"]`.",
		"",
		"**Step 1b — Read the page with " + wikiSourceRef + ", not with a file read**",
		"  Search hands you a slug. " + wikiSourceRef + " turns that slug into content:",
		"  ```",
		"  " + wikiSource + "(project_dir: \"/path/to/project\", path: \"<slug from search>\")",
		"  ```",
		"  Two reasons it comes before your own file tools, and the first one is not about taste:",
		"",
		"  - **It takes the project as a parameter.** You are frequently confined to your own",
		"    workspace, and a page you need may belong to another project in the ecosystem. A file read",
		"    cannot leave your sandbox; this tool reads on your behalf, so a sibling's page is the same",
		"    one call with a different `project_dir`.",
		"  - **It slices.** Same options as " + brand.MCPToolRef("ast", "source") + ": `head`, `tail`,",
		"    `start_line`/`end_line`, `line_numbers`, and `pattern` with `before`/`after` context. A",
		"    long page costs you the part you asked for instead of all of it.",
		"",
		"  ```",
		"  # the summary at the top, and nothing else",
		"  " + wikiSource + "(project_dir: \"/path/to/project\", path: \"auth-flow\", head: 40)",
		"",
		"  # everywhere the page mentions a term, with surrounding lines",
		"  " + wikiSource + "(project_dir: \"/path/to/project\", path: \"auth-flow\", pattern: \"refresh token\", before: 2, after: 4)",
		"",
		"  # a page in the memory wiki instead of the project wiki",
		"  " + wikiSource + "(project_dir: \"/path/to/project\", path: \"<slug>\", wiki: \"memory\")",
		"",
		"  # a page belonging to a sibling project — impossible with a file read from here",
		"  " + wikiSource + "(project_dir: \"<sibling dir>\", path: \"<slug>\")",
		"  ```",
		"",
		"  `path` accepts what the other tools return: the slug, the slug with `.md`, or a path",
		"  relative to the wiki directory — matched case-insensitively, because a slug built from a",
		"  title rarely matches the file name exactly. Guessed wrong? The error lists the pages that",
		"  do exist, which is your answer, not a reason to go back to reading files.",
		"",
		"**Step 2 — Read the frontmatter FIRST (before the body)**",
		"  Every entity page starts with YAML frontmatter. Read it before the body content:",
		"  ```yaml",
		"  ---",
		"  title: Authentication Module",
		"  type: specification",
		"  source: specs/auth.md          # ← provenance: where this came from",
		"  updated: 2026-05-08            # ← freshness check",
		"  confidence: 0.90               # ← trust level (0.0 = no data, 1.0 = rich)",
		"  content_hash: a1b2c3d4e5f6g7h8 # ← change detection",
		"  tags: [knowledge, specification]",
		"  ---",
		"  ```",
		"  - `confidence < 0.5`: treat with caution, verify against source",
		"  - `confidence >= 0.8`: high-quality extraction, trust the summary",
		"  - `updated`: if stale (>30 days), suggest re-indexing",
		"",
		"**Step 3 — Follow [[wikilinks]] to expand context**",
		"  Each page links to related pages. Follow them — they are semantically curated.",
		"",
		"**Step 4 — Expand with cross-references**",
		"  Call " + xrefsRef + " for any entity slug to find all inbound and outbound references.",
		"  This replaces grep for finding \"what else mentions X\" — pre-computed, zero-cost.",
		"",
		"**Step 5 — Verify via provenance**",
		"  Each page has: `*Provenance: ^[source-file.md]*`.",
		"  If you need the raw, uncompiled source — ONLY THEN read the original file.",
		"",
		"**Step 6 — Check communities and god nodes**",
		"  Community pages = thematic clusters. God nodes = most-connected concepts.",
		"",
		"### ❌ Anti-patterns (violations of this protocol)",
		"",
		"| Anti-pattern | Why it is a violation |",
		"|---|---|",
		"| `grep -r \"keyword\" .graphit/knowledge/` | Brute-force scan on a compiled database; ignores all structure |",
		"| Reading docs/ files directly without searching wiki first | Skips the pre-compiled summary, wastes tokens on raw content |",
		"| Using semantic search to find project docs | Wiki search is faster and more precise than embedding search |",
		"| Opening page after page instead of searching | Token bomb; a search returns only what ranked, and the wiki has no files to walk anyway |",
		"| Skipping frontmatter and reading body only | Misses confidence, provenance, type, and freshness metadata |",
		"| Ignoring cross-references and grepping for reverse refs | Cross-refs are pre-computed; grep is O(n) and noisy |",
		"| Answering project questions from model memory | Model memory is stale; wiki is incrementally compiled from truth |",
		"",
		"### 🔄 Fallback to Built-In Tools — ONLY for Topics the Wiki Does Not Cover",
		"",
		"**Your built-in tools (grep, ripgrep, semantic search, file reading) are permitted",
		"ONLY for topics and domains that the wiki does not cover at all.**",
		"The wiki is ALWAYS your primary source. It is NOT a \"first attempt\" — it is",
		"the definitive source. Your tools exist only for domains outside the wiki's scope.",
		"",
		"Your tools are allowed ONLY when ALL of these conditions are true:",
		"",
		"1. You **already searched the wiki** using " + searchRef + ", " + wikiSearchRef + ", or " + browseRef + "",
		"2. You **followed relevant [[wikilinks]]** and checked entity pages",
		"3. You **checked cross-references** using " + xrefsRef + " on the most relevant page",
		"4. The wiki **genuinely has no coverage** of the topic (not indexed, not documented)",
		"5. You **state explicitly** to the user: \"The wiki has no coverage of X, falling back to source search\"",
		"",
		"**If even ONE of these conditions is not met, you MUST NOT use your tools.**",
		"",
		"Examples of valid fallback:",
		"- Wiki has no entity for a newly added module → grep source code for it",
		"- Wiki entity exists but `confidence < 0.3` and content is empty → read raw source via provenance",
		"- Topic is not in docs/ at all (e.g., searching inside test files) → grep is appropriate",
		"",
		"Examples of INVALID fallback (protocol violations):",
		"- Skipping the wiki because \"grep is faster\" → ❌ wiki is pre-compiled and always faster",
		"- Using semantic search without searching wiki first → ❌ wiki search costs ~500 tokens",
		"- Grepping docs/ because you \"didn't find it quickly\" in the wiki → ❌ you must complete all 6 steps first",
		"",
		"### Wiki Paths",
		"",
		"| Scope | How to search |",
		"|---|---|",
		"| **project** (this project) | Call " + searchRef + " or " + browseRef + " |",
		"| **a sibling project in the ecosystem** | Call " + searchRef + " or " + wikiSearchRef + " with **that project's `dir` as `project_dir`** — it has its own compiled wiki |",
		"| **imported context** (hub artifact) | Call " + searchRef + " (context: \"<name>\") |",
		"| **multi-source** (project + memory) | Call " + wikiSearchRef + " (wikis: [\"project\", \"memory\"]) |",
		"| **a Hub artifact, with no project at all** | Call " + searchRef + " (context: \"<id>@<version>\") and **no `project_dir`** |",
		"",
		"### Reading a Hub artifact with no project",
		"",
		"**`project_dir` is optional on the read tools** — " + searchRef + ", " + browseRef + ", " +
			wikiSourceRef + ", " + xrefsRef + ", " + wikiLogRef + " — for the case where there is no",
		"checkout to name: an agent reaching this server over HTTP, working from Hub artifacts alone.",
		"Install the artifact with no project, then address it by its **qualified identifier**:",
		"",
		"```",
		"" + brand.MCPToolName("hub", "install") + "(id: \"<artifact-id>@<version>\")",
		"" + knowledgeSearch + "(context: \"<artifact-id>@<version>\", query: \"<question>\")",
		"" + wikiSource + "(context: \"<artifact-id>@<version>\", path: \"<slug from the search>\")",
		"```",
		"",
		"Two rules come with it:",
		"",
		"- **Without `project_dir`, `context` is not optional** for the knowledge wiki: there is no",
		"  project wiki to fall back on, so a call with neither is refused rather than answered with",
		"  nothing — an empty answer would read as a fact about the documentation.",
		"- **The memory wiki is the exception, and needs neither.** Its user scope is keyed by the",
		"  machine, so `" + wikiSource + "(path: \"<slug>\", wiki: \"memory\")` works with no project at all",
		"  and serves your user memory. A request for the *project* scope without a project is served",
		"  from the user scope, and the answer says so.",
		"",
		"Writing is still project-only: indexing, linting, exporting and installing a context into a",
		"project all need one.",
		"",
		"### 🔒 There is no wiki inside the project — the page file is not yours to open",
		"",
		"Every wiki on this machine is stored **once**, in the global brand directory, keyed by whose",
		"it is:",
		"",
		"```",
		"<global>/wiki/knowledge/project/<project-id>/   this project's documentation wiki",
		"<global>/wiki/knowledge/context/<name>/         an imported documentation set",
		"<global>/wiki/memory/<scope>/<scope-id>/        a memory wiki",
		"```",
		"",
		"There is no `" + brand.DotDir() + "/knowledge` in a project any more, and nothing is copied",
		"into one. A project used to carry a replica of its own wiki plus a full copy of every",
		"imported context, which cost a copy per project and needed resync logic whose only job was to",
		"stop the copies from disagreeing — and when it lost, the project answered from a stale copy",
		"and looked perfectly healthy while doing it.",
		"",
		"What this means for you, concretely:",
		"",
		"- **" + wikiSourceRef + " is the ONLY way to read a page.** Not the preferred way — the only",
		"  one. There is no file under the project to open, and the global directory is outside the",
		"  workspace you are allowed to read. The tool takes the project as a parameter and reads on",
		"  your behalf.",
		"- **It slices, so a long page costs only the part you asked for**: `head`, `tail`,",
		"  `start_line`/`end_line`, `line_numbers`, and `pattern` with `before`/`after` — the same",
		"  options as `" + astSourceTool + "`, for the same reason.",
		"- **Which contexts a project has is a record, not a directory.** It lives in the project's",
		"  context registry, which is why " + listRef + " and " + browseRef + " need a `project_dir` and",
		"  answer differently for two projects sharing one wiki.",
		"- **Writing documentation is unchanged.** You still create and edit markdown under the docs",
		"  tree with your own file tools; it is the *compiled wiki* that moved, not the source.",
		"",
		"### 🔒 Another project's documentation — the ecosystem first, never its files",
		"",
		"When the question is about a different project — *\"how does the auth service issue tokens\"* —",
		"**resolve it in the ecosystem before doing anything else**, then search its wiki with the same",
		"tools you use here:",
		"",
		"```",
		"# 1. resolve the project — never guess the path",
		clusterProjects + "(project_dir: \"/path/to/project\")",
		"",
		"# 2. search ITS wiki, with its dir as project_dir",
		knowledgeSearch + "(project_dir: \"<sibling dir>\", query: \"token issuing\")",
		wikiSearchTool + "(project_dir: \"<sibling dir>\", query: \"how tokens are issued\", wikis: [\"project\", \"memory\"])",
		"",
		"# 3. what documentation it even has, and what changed there lately",
		wikiBrowseTool + "(project_dir: \"<sibling dir>\")",
		wikiLogTool + "(project_dir: \"<sibling dir>\")",
		"",
		"# 4. read the pages it found — with the tool, because a file read cannot leave your workspace",
		wikiSource + "(project_dir: \"<sibling dir>\", path: \"<slug from the search>\")",
		"",
		"# 5. and read the source the wiki pointed you at through the graph, same reason",
		astSourceTool + "(project_dir: \"<sibling dir>\", path: \"<path from the wiki>\")",
		"```",
		"",
		"**Nothing needs to be installed, linked or imported for this.** `project_dir` is a parameter:",
		"pointing these tools at another project is passing a different value, and that is the whole",
		"of it.",
		"",
		"A registered sibling has **its own compiled wiki and its own memories**, so you get ranked",
		"pages and recorded decisions instead of an unfamiliar docs tree to walk. Reading its files, or",
		"grepping them, throws all of that away — and its memories hold the *why* that its documents",
		"often do not state.",
		"",
		"" + wikiLogRef + " is the one to remember: it lists what that project's wiki added, updated and",
		"deleted per sync, so \"what changed over there recently\" is one call rather than a diff you",
		"have to reconstruct.",
		"",
		"The hub skill has the full protocol, including what to do when the project turns out not to be",
		"in the ecosystem. What matters here: **the lookup comes before the reading, and the wiki comes",
		"before the files.**",
		"",
		"### The rest of the knowledge tools",
		"",
		"Search and browse answer \"what does this project say about X\". These four answer questions",
		"*about the wiki itself* — reach for them when the wiki is what looks wrong.",
		"",
		"#### " + listRef + " — every article, by name",
		"```",
		knowledgeList + "(project_dir: \"/path/to/project\")",
		"```",
		"",
		"A flat list of article slugs (`index` and `log` excluded). Use it to answer **\"is there a",
		"page for X at all\"** when " + searchRef + " returned nothing and you need to know whether the",
		"page is missing or merely ranked low — a search miss and an absent page are different",
		"problems with different fixes. It carries no summaries; " + browseRef + " is the catalogue",
		"with types and confidence.",
		"",
		"#### " + lintRef + " — audit the wiki's structure",
		"```",
		knowledgeLint + "(project_dir: \"/path/to/project\")",
		knowledgeLint + "(project_dir: \"/path/to/project\", stale_days: 90)",
		"```",
		"",
		"Reports orphan pages, broken links and stale pages (default: older than 30 days).",
		"`stale_days` is the only knob: every other finding is read off the index, which either has",
		"the edge or does not.",
		"",
		"**It reports and never repairs, and that is not a missing feature.** The one mechanically",
		"repairable finding used to be a page whose `## Backlinks` section did not match its inbound",
		"references — and there is no page to repair now, nor can the `xrefs` table be missing an edge",
		"the graph knows about, because the graph is built FROM it. A broken `[[wikilink]]` is the",
		"remaining class, and it needs a human decision about which page was meant.",
		"",
		"Run it when a documentation task is finished and you want to know whether what you wrote",
		"actually connected to the rest of the wiki.",
		"",
		"#### " + schemaRef + " — where the wiki lives",
		"```",
		knowledgeSchema + "(project_dir: \"/path/to/project\")",
		"```",
		"",
		"Returns the wiki directory and confirms the architecture is a file-based wiki, not a graph",
		"database. Useful for one thing: telling apart \"the wiki is empty\" from \"I am pointed at the",
		"wrong project\". Do not expect node labels — that is " + brand.MCPToolRef("ast", "schema") + ".",
		"",
		"#### " + exportRef + " — publish this project's wiki to the Hub",
		"```",
		knowledgeExport + "(project_dir: \"/path/to/project\")",
		"```",
		"",
		"Pushes the docs tree and the compiled wiki to a Hub branch, where other projects can install",
		"it as a knowledge context. This writes to a shared repository — **only when the user asks",
		"for it.** It is the counterpart of " + knowledgeInstallRef + ", which is how a context arrives",
		"from the other direction.",
		"",
		"To drop an imported context you no longer want, call " + removeRef + " with its `context` name.",
		"Called **without** `context` it clears this project's own wiki instead, so always pass one",
		"unless wiping the local wiki is precisely the request.",
	}

	lines = append(lines,
		"",
		"### What the wiki reads — and what to do when a document is missing from it",
		"",
		"The wiki is built from **`"+docsDir+"/` plus the project's root `README.md`**, and nothing",
		"else. A document outside those two is not in the wiki, which is not a bug and not a stale",
		"index: it was never in scope. Before concluding a page is missing, check where the page's",
		"source actually lives.",
		"",
		"| What you want | The key | Default |",
		"|---|---|---|",
		"| documentation kept somewhere other than `"+docsDir+"/` | `knowledge.docs_dir` | `docs` |",
		"| the whole project indexed, as it was before this default | `knowledge.docs_dir` = `.` | — |",
		"| the root README left out | `knowledge.include_readme` = `false` | on |",
		"| the docs tree in the **code** graph as well | `ast.index_docs` = `true` | off |",
		"",
		"So a document that belongs in the wiki goes **under `"+docsDir+"/`**. Writing it anywhere else",
		"and then reporting that the wiki did not pick it up is a scope error, not an indexing one.",
		"",
		"### Reindexing is automatic — do not call sync in the normal flow",
		"",
		"The daemon watches the docs tree and rebuilds the wiki when a file changes. After",
		"you edit, create, rename, or delete anything under `docs/`, **there is nothing to",
		"call**. Reindexing costs a second or two and happens without you.",
		"",
		"Calling "+syncRef+" after every edit is the most common way this module gets",
		"misused: it duplicates work the watcher is already doing and, on a large docs tree,",
		"makes the agent wait on a rebuild it did not need.",
		"",
		"> The one exception is not mid-session and is not yours to decide: a session that changed",
		"> code ends with a single "+syncRef+", which the AST skill makes mandatory. It rebuilds this",
		"> wiki along with the code graph and the memory wikis, so the task log you just wrote is",
		"> covered by that call. Everything below is about the situations that come up *before* it.",
		"",
		"**Call "+syncRef+" only when the watcher cannot have seen the change:**",
		"",
		"| situation | why the watcher missed it |",
		"|---|---|",
		"| the daemon is not running | nothing is watching |",
		"| docs were changed by something outside this machine — a pull, a checkout, a restore | the daemon was down, or the change landed as one bulk event |",
		"| a search returns something you know is stale, minutes after the edit | the rebuild failed; sync surfaces the error |",
		"| **you need CERTAINTY that what you are about to read is current** | the rebuild is asynchronous and lands after the write — see below |",
		"",
		"### The rebuild lands AFTER the write — so certainty is a call, not an assumption",
		"",
		"\"Automatic\" is not \"instant\". The watcher notices the change, waits out its debounce, and",
		"only then rebuilds — so there is a window, short but real, in which the page you just wrote",
		"is on disk and not yet in the index. A search inside that window does not warn you: it",
		"answers from the previous state, with the same confidence it would have if it were current.",
		"That is the failure mode to guard against, because a stale answer and a fresh one are",
		"indistinguishable from where you are standing.",
		"",
		"The rule that follows is narrow, and it is not \"sync after every edit\":",
		"",
		"| you are about to | do this |",
		"|---|---|",
		"| keep editing, mid-task | nothing — the watcher will catch up while you work |",
		"| **decide something on the basis of what a tool returns**, right after a write | call "+syncRef+" and let it finish, then read |",
		"| **report the work as done** | call "+syncRef+" once — the AST skill already makes this mandatory |",
		"| read after a change that was not your own edit — a pull, a checkout, a rebase, a restore | call "+syncRef+" |",
		"",
		"When only this wiki is in question, "+knowledgeSyncRef+" is the narrower call and reaches the",
		"same certainty for a fraction of the work; "+syncRef+" is what puts the knowledge index, the",
		"memory index and the AST graph at the same point, which is what you want before concluding",
		"anything that spans more than one of them.",
		"",
		"### First check whether anything is watching at all",
		"",
		"The first row of that table is a **question, not an assumption** — and "+daemonStatusRef+" is",
		"how you answer it:",
		"",
		"```",
		daemonStatus+"()",
		"```",
		"",
		"No `project_dir`: the daemon is global, one process for every project on the machine. What",
		"comes back and what to do with it:",
		"",
		"| Field | What it tells you |",
		"|---|---|",
		"| `running` | `false` means **nothing has been reindexing anything.** Every staleness symptom in this section is explained, and reindexing by hand is the only route until the daemon is back |",
		"| `uptime_seconds` | Started after your edit? Then it never saw the edit — the watcher only knows about changes made while it was alive |",
		"| `recent_logs` | The last ten lines, which is where a failed rebuild says why it failed |",
		"| `pid`, `pid_file_path` | Which process, and the file that tracks it |",
		"",
		"**Check status before reporting a stale index to the user**, and before concluding a module",
		"is broken. \"The wiki is out of date\" and \"the daemon is down\" look identical from where you",
		"are standing, and only one of them is a bug.",
		"",
		"### The transient failure that looks like a missing index",
		"",
		"The daemon holds a write lock while it reindexes. A read that lands in that window fails —",
		"and the message names the database, which reads exactly like \"there is no index here\":",
		"",
		"```",
		"ladybug open: failed to open database with status 1",
		"```",
		"",
		"**That is a lock, not an absence. Retry it.** The same query succeeds seconds later. Treating",
		"it as \"no index\" and falling back to grep is the single most expensive way to misread this",
		"framework — you abandon the graph precisely because it was busy building itself. If retries",
		"keep failing, then call "+daemonStatusRef+": a daemon stuck mid-reindex shows up in",
		"`recent_logs`.",
		"",
		"### Stopping it",
		"",
		"```",
		daemonStop+"()",
		"```",
		"",
		"Sends SIGTERM, waits ten seconds, then SIGKILL. **Do this only when the user asks.** Stopping",
		"the daemon turns off automatic reindexing for every project on the machine, and takes the",
		"overnight dream sessions with it — after which everything in this skill that says",
		"\"reindexing is automatic\" stops being true.",
		"",
		"```",
		syncTool+"(project_dir: \"/path/to/project\")",
		"```",
		"",
		"Fire-and-forget: do not wait for it, continue working.",
		"",
		"**When only the wiki is suspect, "+knowledgeSyncRef+" is the narrower tool** — it rebuilds",
		"the wiki from the docs tree and nothing else, where "+syncRef+" also reindexes the AST",
		"graph, both memory wikis, and the Hub. Same fix, a fraction of the work:",
		"",
		"```",
		knowledgeSync+"(project_dir: \"/path/to/project\")",
		"",
		"# Re-pull one imported context after it changed upstream in the Hub",
		knowledgeSync+"(project_dir: \"/path/to/project\", context: \"<name>\")",
		"```",
		"",
		"**What IS mandatory is the record itself.** A change without its task log is",
		"incomplete — that obligation is about writing the documentation, not about",
		"reindexing it.",
		"",
		"## Documentation Requirements",
		"",
		"### Architecture Documentation",
		"- Update docs/architecture/ when changing system structure, adding modules, or modifying dependencies.",
		"- Maintain accurate component diagrams (PlantUML) showing current module relationships.",
		"- Document API boundaries and integration points.",
		"",
		"### Decision Records",
		"- When making a non-trivial architectural decision, create an ADR in docs/decisions/.",
		"- ADR format: ## Status, ## Context, ## Decision, ## Consequences.",
		"",
		"### Technical Documentation",
		"- Keep docs/ files accurate when modifying the systems they describe.",
		"- Update function/module descriptions when behavior changes.",
		"",
		"### Feature Specifications",
		"- Create detailed spec files in `docs/specs/` for new features and maintain it updated with future evolution.",
		"- A spec can be a detailed markdown file describing: purpose, scope, inputs/outputs, and acceptance criteria.",
		"- Specs improve discoverability and serve as context for future sessions.",
		"- Use filenames like `docs/specs/<feature-name>.md`.",
		"",
		"### 🔒 MANDATORY: Task Logs — Continuity for Multi-Agent & Multi-Session Work",
		"",
		"> **Every task you perform MUST be logged in `docs/tasks/`.** This is your",
		"> institutional memory. Another agent — or you in a future session — MUST be able",
		"> to read your task log and continue exactly where you left off, resolve remaining",
		"> technical debts, or understand every trade-off you made.",
		"",
		"#### Purpose",
		"",
		"Task logs serve as the **detailed operational journal** of the project. They capture",
		"the same level of detail that agents record in their native conversation artifacts,",
		"but persisted in the project's documentation — accessible to any agent, any IDE,",
		"any session. Without task logs, institutional knowledge is lost between sessions.",
		"",
		"#### When to create or update a task log",
		"",
		"| Scenario | Action |",
		"|---|---|",
		"| **Before starting any task** — before the first edit, not after the last | Create `docs/tasks/<task-name>.md` with the objective, the reasoning, and the plan, at `status: in-progress` |",
		"| Finishing a step, or marking one item of the plan done | Tick the item, append to `## Progress Log`, bump `updated:` |",
		"| Changing course — a different approach, a dropped item, a new constraint | Rewrite the affected plan items and record WHY the old one was abandoned |",
		"| Being interrupted, corrected, or asked to redo work | Read the log, record the correction and the new direction, then continue |",
		"| Continuing a previously started task | Update the existing task log with new progress |",
		"| Finishing a task | Update status to `done`, document final state and remaining debts |",
		"| Discovering technical debt during any work | Add to the relevant task log's `## Technical Debt` section |",
		"| Making a trade-off or shortcut | Document it immediately in `## Trade-offs & Decisions` |",
		"",
		"> 🔒 **Every file path you write into a task log — in `## Files Changed` or anywhere",
		"> else — MUST be relative to the project root, never an absolute path on this machine.**",
		"> Write `internal/auth/handler.go`, not `/home/you/projects/app/internal/auth/handler.go`.",
		"> An absolute path is only true on the machine that wrote it — the next agent, session, or",
		"> teammate opens the same project from a different path, and the log becomes unreadable or,",
		"> worse, silently points at the wrong file.",
		"",
		"#### 🔒 The task log OPENS the task — it is not a report you write at the end",
		"",
		"**Your first action on any task is to write its log, before you edit a single file.** Not a",
		"placeholder: the log opens with everything the work is about to be based on, so that the",
		"decision to do it this way survives even if nothing else does.",
		"",
		"| At creation, the log carries | Concretely |",
		"|---|---|",
		"| The objective | what is being asked, in full, including the part the request only implies |",
		"| Your reasoning | how you read the request, what you already know from memory, the wiki and the graph, and what that ruled in |",
		"| The justification | why THIS approach — and which alternatives you considered and dropped, with the reason |",
		"| The plan, as tasks | `## Plan & Task Breakdown`: one checkbox per task, in the order you intend to do them |",
		"| A spec per task | for each one: what it touches, what \"done\" means for it, and the constraint or invariant it must respect |",
		"",
		"Writing it first is not ceremony — it is the only version of this document that can help",
		"anyone. A log written at the end describes work that already exists; a log written at the",
		"start is the thing that lets someone else finish it. If the session dies mid-task — and",
		"sessions do — the end-written log was never written at all.",
		"",
		"**Then keep it current as you go. The trigger to update is not the end of the task:**",
		"",
		"- a step finished — tick it, and say in `## Progress Log` what actually happened",
		"- the direction changed — record the new plan AND why the old one was wrong, not just the new one",
		"- you hit a blocker — write it down with what you tried, so the next agent does not retry it",
		"- you learned something non-obvious about the system — `## System Knowledge`, in the same turn",
		"- you took a shortcut — `## Technical Debt`, with enough context to resolve it later",
		"",
		"> **The standard the log has to meet, at every moment — not only at the end:** if your",
		"> session ended right now, without warning, could another agent open this file and continue",
		"> the work from it — knowing what is done, what is next, what was decided and what was",
		"> deliberately not done — with no access to your conversation? If the answer is no, the log",
		"> is behind the work, and bringing it up to date is the next thing you do, before more code.",
		"",
		"`## Progress Log` is append-only. Never delete an entry to make the trajectory look",
		"cleaner: an abandoned approach that is still recorded is what stops the next agent from",
		"trying it again.",
		"",
		"#### 🔒 Resuming after an interruption, a correction, or a change of course",
		"",
		"When you are interrupted, when the user asks for changes or fixes to work you already did,",
		"or when the direction changes mid-task, the resumption has its own protocol — and its first",
		"two steps are not about code:",
		"",
		"1. **Read the existing task log first.** It is the record of what was actually done, which",
		"   is not the same as what you remember doing — and after an interruption, memory is the",
		"   least reliable source available to you.",
		"2. **Re-open the skills and re-run the lookups.** A correction does not suspend this",
		"   framework's tool priority — it re-applies it in full. Memory, the wiki and the graph come",
		"   before your native tools on the resumed turn exactly as on the first one. Urgency is the",
		"   reason agents drop this, and urgency is not one of the fallback conditions.",
		"3. **Record the interruption in the log** — the correction, the reason, and what the plan is",
		"   now — before you continue, in `## Progress Log` and in the affected plan items.",
		"4. **Then continue the work.**",
		"",
		"A resumed task whose log still describes the pre-correction plan is worse than no log: it",
		"sends the next agent to do work the user already rejected.",
		"",
		"#### Quick Task Log (for minor changes)",
		"",
		"For minor fixes, small features, or routine changes, use this minimal format.",
		"This is the **minimum acceptable** documentation — never skip it. It is still created",
		"BEFORE the change, at `status: in-progress`, and flipped to `done` once the change lands;",
		"a minor change is not an exemption from opening the log, only from planning it formally.",
		"",
		"```markdown",
		"---",
		"title: <Descriptive task title>",
		"status: in-progress | done",
		"created: <YYYY-MM-DD>",
		"updated: <YYYY-MM-DD>",
		"---",
		"",
		"# <Task Title>",
		"",
		"## Objective",
		"<2-3 sentences: what was the goal?>",
		"",
		"## Files Changed",
		"| File | Change | Reason |",
		"|---|---|---|",
		"| `path/to/file` | Modified/Created | <why> |",
		"",
		"## Key Decisions",
		"- <Decision 1 and rationale>",
		"",
		"## Notes",
		"- <Any non-obvious discoveries or gotchas>",
		"```",
		"",
		"Use the **full template** below for major features, architectural changes, or complex refactors.",
		"",
		"#### Full Task Log Template",
		"",
		"For significant work, every task log MUST follow this structure:",
		"",
		"```markdown",
		"---",
		"title: <Descriptive task title>",
		"status: in-progress | done | blocked",
		"created: <YYYY-MM-DD>",
		"updated: <YYYY-MM-DD>",
		"tags: [<relevant>, <tags>]",
		"---",
		"",
		"# <Task Title>",
		"",
		"## Objective",
		"<What was the goal? What problem was being solved? Include full context so a new",
		"agent can understand the task without reading the original conversation. Written at",
		"creation, before the work: the objective, your reasoning about it, and why this",
		"approach rather than the alternatives you dropped.>",
		"",
		"## Plan & Task Breakdown",
		"<Written BEFORE the work starts, and kept current as it proceeds. One checkbox per",
		"task, in the order you intend to execute them, each with its own spec: what it",
		"touches, what 'done' means for it, and the constraint or invariant it must respect.",
		"",
		"- [ ] **T1 — <task title>** — Spec: <files/entities it touches; the acceptance",
		"  condition; the constraint that makes it non-obvious>",
		"- [ ] **T2 — <task title>** — Spec: <...>",
		"",
		"Tick items as they land. When the plan changes, rewrite the affected item and record",
		"in the Progress Log WHY the previous one was abandoned — never silently delete it.>",
		"",
		"## Implementation Details",
		"<What was done? Be extremely specific:",
		"- Which files were created/modified/deleted and why",
		"- What approach was chosen and why",
		"- Key code patterns or algorithms used",
		"- Configuration changes made",
		"- Dependencies added or removed",
		"- Edge cases handled or deliberately not handled>",
		"",
		"## Use Cases",
		"",
		"> **🔒 MANDATORY — Document ALL use cases implemented, modified, or affected.**",
		"> This section MUST be complete and always kept up-to-date on any future change.",
		"> A use case is NOT documented until it has: actor, preconditions, main flow,",
		"> alternative flows, postconditions, and error scenarios.",
		"",
		"<List EVERY use case covered by this task. Each use case MUST follow this structure:",
		"",
		"### UC-XX: <Use Case Title>",
		"- **Actor**: <Who triggers this — user, system, agent, cron, etc.>",
		"- **Preconditions**: <What must be true before this use case can execute>",
		"- **Main Flow**:",
		"  1. <Step-by-step description of the happy path>",
		"  2. <Each step must be concrete and actionable>",
		"  3. <Include the exact functions/methods/endpoints involved>",
		"- **Alternative Flows**:",
		"  - <Variations from the main flow — e.g., optional parameters, different input types>",
		"- **Error Scenarios**:",
		"  - <What happens when X fails — error codes, fallback behavior, user feedback>",
		"- **Postconditions**: <What is true after successful execution>",
		"- **Affected Files**: <List of source files that implement this use case>",
		"",
		"Rules for use case documentation:",
		"- NEVER skip a use case. If you implemented it, document it.",
		"- NEVER write vague use cases like 'user can do X'. Be specific about HOW.",
		"- When modifying an existing task log, UPDATE existing use cases to reflect changes",
		"  and ADD new use cases introduced by the modification.",
		"- When a use case is removed or deprecated, mark it clearly with [DEPRECATED] and",
		"  explain why.>",
		"",
		"## Test Cases & Acceptance Criteria",
		"",
		"> **🔒 MANDATORY — Write ALL test cases and acceptance criteria using BDD/Gherkin syntax.**",
		"> Every use case MUST have at least one corresponding test scenario.",
		"> Test cases MUST be kept up-to-date on any future change — they are living",
		"> documentation that validates the system's behavior.",
		"",
		"<Write test scenarios using BDD (Behavior-Driven Development) Gherkin syntax.",
		"Each scenario validates one specific behavior. Use the structured keywords:",
		"",
		"- **Given** (Dado): Defines the initial context, state, or precondition.",
		"- **When** (Quando): Defines the action executed by the actor.",
		"- **Then** (Então): Defines the expected result or consequence.",
		"- **And** / **But**: Adds more context, actions, or results without repeating keywords.",
		"",
		"### Feature: <Feature Name>",
		"Ref: <Link to use case UC-XX or requirement>",
		"",
		"#### Scenario: <Descriptive scenario name — happy path>",
		"```gherkin",
		"Given <initial state or precondition>",
		"  And <additional context if needed>",
		"When <the actor performs the action>",
		"  And <additional action if needed>",
		"Then <expected outcome>",
		"  And <additional verification if needed>",
		"```",
		"",
		"#### Scenario: <Descriptive scenario name — error case>",
		"```gherkin",
		"Given <initial state or precondition>",
		"When <the actor performs an invalid action>",
		"Then <expected error behavior>",
		"  And <system remains in consistent state>",
		"```",
		"",
		"#### Scenario Outline: <Parameterized scenario name>",
		"```gherkin",
		"Given <parameterized precondition with \"<param>\">",
		"When <action with \"<input>\">",
		"Then <expected result with \"<output>\">",
		"",
		"Examples:",
		"  | param   | input   | output   |",
		"  | value1  | data1   | result1  |",
		"  | value2  | data2   | result2  |",
		"```",
		"",
		"Rules for test case documentation:",
		"- **One objective per test**: Each scenario tests ONE specific behavior. Do not",
		"  combine multiple validations in a single scenario.",
		"- **Independence**: Scenarios MUST NOT depend on the success of other scenarios.",
		"  Each scenario must be executable in isolation and in any order.",
		"- **Traceability**: Every scenario MUST reference the use case (UC-XX) or",
		"  requirement it validates via the `Ref:` field.",
		"- **Specific data**: NEVER write 'insert any text'. Specify exact test data",
		"  (e.g., 'a string with 255 alphanumeric characters') when the data itself",
		"  is what is being validated.",
		"- **Clarity**: Any team member (even new) must be able to read and understand",
		"  the scenario without asking questions. Avoid jargon and ambiguity.",
		"- **Cover all paths**: Write scenarios for happy paths, error cases, edge cases,",
		"  and boundary conditions. A use case without error scenarios is INCOMPLETE.",
		"- **Boundary Value Analysis (BVA)**: When a use case involves numeric ranges,",
		"  string lengths, collection sizes, dates, or any constrained input, you MUST",
		"  write scenarios that test the exact boundary values — minimum, minimum+1,",
		"  maximum-1, maximum, and out-of-range values (below minimum, above maximum).",
		"  Use `Scenario Outline` with an `Examples` table to cover boundaries concisely.",
		"- **Keep updated**: When implementation changes, update the corresponding test",
		"  scenarios immediately. Stale tests are worse than no tests.>",
		"",
		"## Files Changed",
		"| File | Change | Reason |",
		"|---|---|---|",
		"| `path/to/file.go` | Modified | <what changed and why> |",
		"| `path/to/new.go` | Created | <purpose of new file> |",
		"",
		"## Trade-offs & Decisions",
		"<Document EVERY trade-off made during implementation:",
		"- Why option A was chosen over option B",
		"- Performance vs. simplicity decisions",
		"- Scope reductions and their justification",
		"- Temporary workarounds and why they were necessary>",
		"",
		"## Technical Debt",
		"<List ALL known technical debt created or discovered:",
		"- [ ] <Debt item 1> — <why it exists, impact, suggested fix>",
		"- [ ] <Debt item 2> — <why it exists, impact, suggested fix>",
		"Mark items as [x] when resolved in future tasks.>",
		"",
		"## System Knowledge",
		"<Record any insights about the system discovered during this task:",
		"- Non-obvious behaviors or gotchas",
		"- Undocumented dependencies or coupling",
		"- Performance characteristics observed",
		"- Configuration quirks or edge cases",
		"- Anything a future agent would need to know to work in this area>",
		"",
		"## Progress Log",
		"<Chronological log of work done. Add entries — never delete previous ones.",
		"This enables a new agent to understand the full trajectory.>",
		"",
		"### <YYYY-MM-DD>",
		"- <What was accomplished>",
		"- <Blockers encountered and how they were resolved>",
		"- <Next steps planned>",
		"```",
		"",
		"#### Quality requirements for task logs",
		"",
		"- **Completeness**: Another agent reading ONLY the task log (without conversation",
		"  history) must be able to understand what was done, why, and what remains.",
		"- **Specificity**: Use exact file paths, function names, line numbers, and code",
		"  snippets. Vague descriptions like 'updated the module' are UNACCEPTABLE.",
		"- **Use case coverage**: The `## Use Cases` section MUST list ALL use cases",
		"  implemented or modified. Each use case MUST have: actor, preconditions, main flow,",
		"  alternative flows, error scenarios, postconditions, and affected files. Use cases",
		"  MUST be kept up-to-date whenever the implementation changes — treat them as living",
		"  documentation, not a one-time snapshot.",
		"- **Test case coverage**: The `## Test Cases & Acceptance Criteria` section MUST",
		"  contain BDD/Gherkin scenarios for EVERY use case. Each scenario MUST be independent,",
		"  traceable to a use case (Ref: UC-XX), and use specific test data. Cover happy paths,",
		"  error cases, and boundary conditions. Test cases MUST be updated whenever the",
		"  implementation or use cases change.",
		"- **Written first, not last**: The log exists before the first edit — objective,",
		"  reasoning, justification and plan — because that is the version of it another agent",
		"  can act on. A log assembled at the end is a report, and if the session is cut short",
		"  it is a document that never existed.",
		"- **Currency**: The log is updated at every step that lands, every change of course,",
		"  and every blocker — not in one pass at the end. At any moment it must answer \"where",
		"  did this stop and what is next\" for someone who was never in the conversation.",
		"- **Continuity**: If a task spans multiple sessions, each session MUST append to",
		"  the Progress Log and update the status, technical debt, use cases, test cases, and",
		"  implementation details. A session resumed after an interruption or a correction",
		"  records the correction and the resulting plan change before continuing the work.",
		"- **Debt tracking**: Every shortcut, TODO, FIXME, or known limitation MUST appear",
		"  in the Technical Debt section with actionable context for resolution.",
		"- **System knowledge**: Discoveries about non-obvious system behavior MUST be",
		"  recorded, even if they seem minor. These are the insights that prevent future",
		"  agents from repeating your investigation work.",
		"",
		"#### Naming convention",
		"",
		"- Use kebab-case: `docs/tasks/fix-memory-sync-race-condition.md`",
		"- Be descriptive: prefer `migrate-hub-to-branch-per-artifact.md` over `hub-refactor.md`",
		"- Group related sub-tasks under a single task log when they share the same objective",
		"",
		"#### Relationship to other docs",
		"",
		"- Task logs complement — not replace — architecture docs, ADRs, and specs.",
		"- If a task results in an architectural change, BOTH the task log AND the",
		"  architecture doc must be updated.",
		"- If a task involves a design decision, create an ADR in `docs/decisions/` AND",
		"  reference it from the task log's Trade-offs section.",
		"- Task logs are the \"how it happened\" — specs and ADRs are the \"what it is\",",
		"",
		"#### Task backlog — task registration is independent of Dream",
		"",
		"The task backlog records work that should survive the current conversation or session.",
		"It lives in `docs/tasks/backlog/` by default and is managed through:",
		"",
		"```",
		brand.MCPToolRef("backlog", "list")+"(project_dir: \"/path/to/project\")",
		brand.MCPToolRef("backlog", "add")+"(project_dir: \"/path/to/project\", title: \"<task>\", body: \"<self-contained brief>\")",
		brand.MCPToolRef("backlog", "remove")+"(project_dir: \"/path/to/project\", slug: \"<slug>\")",
		"```",
		"",
		"**Dream never consumes backlog items.** Recording, listing, and removing tasks works",
		"whether Dream is enabled, disabled, running, or absent. Dream improves project knowledge;",
		"the backlog only records tasks for an agent or user to perform through a separate workflow.",
		"",
		"Write every backlog body for a reader with no conversation history: name the paths, the",
		"problem, relevant constraints, what has already been ruled out, and how completion will",
		"be verified. Check the list before adding so the same task is not recorded twice.",
	)

	lines = append(lines,
		"---",
		"",
		"> **Note:** The section below covers integration and interface documentation specifically.",
		"> It applies whenever the project you are working on exposes or consumes any system interface",
		"> — whether this project is a framework, a library, a CLI tool, or an end-user application.",
		"> \"External system\" means any system boundary, including internal module-to-module interfaces.",
		"",
		"# Integration Documentation Maintenance Rule",
		"",
		"## ⚠️ MANDATORY PRE-FLIGHT: Hub-First Integration Protocol",
		"",
		"> **NEVER assume anything about an external system's API, schema, field names, types,",
		"> endpoints, error codes, authentication, or behavior.**",
		"> The hub is the single source of truth for all external integrations.",
		"",
		"> 🔒 **This protocol is not only for code you are about to write.** It applies the moment the",
		"> user names a system that is not this project's own code — \"how does <system> handle X\",",
		"> \"does <system> have a feature for Y\", \"look at how <system> does Z\". Answering that from",
		"> model memory is the same mistake as coding an integration from memory. Run the steps below",
		"> BEFORE you answer, not only before you implement.",
		"",
		"### Before implementing an integration — or answering a question about one:",
		"",
		"**Step 0 — Check what this project already has installed from the Hub:**",
		"",
		"Knowledge contexts already installed here: "+installedContexts+".",
		"",
		"If the named system is already in that list, skip straight to Step 3 — it is installed, there",
		"is nothing to search or install. Query it directly:",
		"```",
		knowledgeSearch+"(project_dir: \"/path/to/project\", query: \"<your question>\", context: \"<name from the list>\")",
		"```",
		"That list is not exhaustive across every artifact type: the same system may also exist as an",
		"`ast` context (its source, not just its docs) — check "+brand.MCPToolRef("ast", "list")+" too",
		"when the question is about behavior a doc page would not capture.",
		"",
		"**Step 1 — Not installed? Search the hub for an existing knowledge artifact using the "+hubSearchRef+" tool:**",
		"",
		"```",
		hubSearch+`(query: "<the system's name>", type: "knowledge")`,
		"```",
		"",
		"Search by the system's name — that is what you have and what the artifact is registered under.",
		"No `project_dir`: the registry is global. If the name returns nothing, widen the term before",
		"giving up (the match is a substring, not a semantic search), and only then fall back to",
		hubListRef+" for the whole `knowledge` catalogue.",
		"",
		"**Step 2 — If found, install it immediately using the "+knowledgeInstallRef+" tool (passing absolute `project_dir` and the context `name`):**",
		"",
		"```",
		knowledgeInstall+"(project_dir: \"/path/to/project\", name: \"<artifact-name>\")",
		"```",
		"",
		"This installs the artifact at "+dotBrand+"/knowledge/<name>/.",
		"",
		"**Step 3 — Read the installed wiki before writing a single line of code, or answering the user.**",
		"",
		"**Step 4 — Use the installed knowledge integration documentation as the ONLY source of truth:**",
		"",
		"- All field names, types, and structures come from the documentation — never from memory or guessing",
		"- All endpoint paths, methods, and parameters come from the documentation",
		"- All authentication schemes come from the documentation",
		"- If the documentation is ambiguous, always stay user informed about the ambiguity and your assumptions about it",
		"",
		"---",
		"",
		"## 🔒 MANDATORY: Every System Interface MUST Be Documented",
		"",
		"**Every interface, integration, or data exchange mechanism that this system",
		"provides or consumes — regardless of paradigm or transport — MUST have a",
		"complete, formal specification file in `docs/`.**",
		"",
		"There are **NO exceptions**. If the system communicates with the outside world",
		"(or between internal services) through ANY of the following mechanisms, it",
		"MUST be documented:",
		"",
		"| Mechanism | Examples | Required Action |",
		"|---|---|---|",
		"| **REST / HTTP APIs** | Endpoints consumed or exposed | OpenAPI spec (`.yaml`) |",
		"| **File Processing** | CSV/JSON/XML ingestion, S3 dumps, FTP drops, batch imports/exports | JSON Schema for the file format (`.json`) |",
		"| **gRPC / RPC** | Internal or external service calls | Protobuf definition (`.proto`) |",
		"| **Messaging / Events** | Kafka topics, SQS queues, RabbitMQ, SNS, event buses | AsyncAPI spec (`.yaml`) |",
		"| **GraphQL** | Queries, mutations, subscriptions | GraphQL SDL (`.graphql`) |",
		"| **WebSockets** | Real-time bidirectional channels | AsyncAPI spec (`.yaml`) |",
		"| **Webhooks** | Inbound or outbound HTTP callbacks | OpenAPI callbacks (`.yaml`) |",
		"| **SOAP / Legacy** | WSDL-based web services | WSDL (`.xml`) |",
		"| **Database Connections** | External databases, data warehouses, read replicas | Connection spec + schema doc (`.md`) |",
		"| **CLI / Shell Interfaces** | Commands invoked by the system or exposing its functionality | Interface doc (`.md`) |",
		"| **SDK / Library Integrations** | Third-party SDKs, client libraries, native modules | Integration doc (`.md`) with API surface |",
		"| **Email / Notification** | SMTP, SendGrid, push notifications, SMS | Payload schema + provider doc (`.md`) |",
		"| **OAuth / Auth Providers** | SSO, OIDC, SAML, API keys, token exchanges | Security scheme doc (`.yaml` or `.md`) |",
		"| **Scheduled Jobs / Cron** | Periodic tasks that interact with external resources | Trigger + payload doc (`.md`) |",
		"",
		"### Rules",
		"",
		"- **NEVER** leave an integration undocumented. If you discover the system",
		"  interacts with an external service, file format, or internal subsystem",
		"  that lacks documentation — **create the spec immediately**.",
		"- **NEVER** implement a new integration without first creating its specification.",
		"  The spec is written BEFORE the code, not after.",
		"- **When modifying an existing integration**, update the specification FIRST,",
		"  then implement the changes.",
		"- **File-based integrations are integrations.** A CSV import, a JSON config",
		"  file, or a batch export is just as important as a REST endpoint —",
		"  document the schema, fields, formats, and constraints.",
		"- **Internal service boundaries are integrations.** If two modules communicate",
		"  through a defined interface (even in-process), document it.",
		"- **Treat specs as first-class code artifacts** — they are versioned, reviewed,",
		"  and maintained with the same rigor as source code.",
		"",
		"## 🔒 MANDATORY: Wiki-First Knowledge Retrieval — Replaces Your Tools",
		"",
		"> **The knowledge wiki REPLACES your built-in search tools for understanding API",
		"> contracts, schemas, endpoints, and external system interfaces.**",
		"> **NEVER use grep, ripgrep, semantic search, or file-by-file reading to answer",
		"> questions about integrations, endpoints, schemas, or external services.**",
		"> **ALWAYS consult the wiki FIRST. Only fall back to raw spec files when the wiki",
		"> explicitly points you there via provenance links.**",
		"",
		"### Why this replaces your tools",
		"",
		"The knowledge wiki is **compiled at index time** with BM25 scoring, cross-references,",
		"backlinks, confidence scores, and provenance markers. Your built-in tools operate on",
		"**raw spec files** (YAML, proto, graphql) — they cannot match the navigability of",
		"a compiled, cross-referenced wiki.",
		"",
		"| Your tool | Wiki equivalent | Why wiki wins |",
		"|---|---|---|",
		"| `grep -r \"endpoint\" docs/` | Call "+searchRef+" → find endpoint → read page | Wiki: 1 search. Grep: scans all spec files |",
		"| Reading raw OpenAPI YAML directly | Read wiki entity page (pre-summarized) | Wiki: structured summary with confidence. YAML: verbose, noisy |",
		"| `grep` for \"which APIs use this schema\" | Call "+xrefsRef+" on schema entity | Wiki: instant reverse lookup. Grep: O(n) scan |",
		"| Listing docs/ to find specs | Call "+browseRef+" → scan by paradigm type | Wiki: grouped catalog. ls: flat listing with no context |",
		"",
		"### 🔒 When you MUST use the wiki (MANDATORY — no exceptions)",
		"",
		"| Scenario | What to do | What NOT to do |",
		"|---|---|---|",
		"| **Finding an API endpoint** | Call "+searchRef+" → find the spec page → read it | ❌ Don't grep YAML files for path strings |",
		"| **Understanding a schema** | Call "+searchRef+" → find schema entity → read it | ❌ Don't open raw .yaml and search for `schemas:` |",
		"| **Finding which APIs use a model** | Call "+xrefsRef+" on entity → get cross-references | ❌ Don't grep for `$ref` across all YAML files |",
		"| **Checking if a integration exists** | Call "+browseRef+" → scan the catalog | ❌ Don't use `find` or `ls` on docs/ |",
		"| **Understanding auth for an API** | Read the spec entity page → check security section | ❌ Don't grep for \"security\" across all specs |",
		"| **Checking API versioning** | Read entity frontmatter → check `updated` and `source` | ❌ Don't read raw spec version fields |",
		"| **Verifying field names and types** | Read entity page → follow provenance to raw spec | ❌ Don't guess from model memory |",
		"",
		"### When you should NOT use the wiki",
		"",
		"| Scenario | Use instead |",
		"|---|---|",
		"| Writing or editing spec files (.yaml, .proto, .graphql) | File edit tools |",
		"| Finding where an integration is implemented in this codebase | The **AST graph** — "+brand.MCPToolRef("ast", "search")+" then "+brand.MCPToolRef("ast", "query")+", not grep |",
		"| Reading that implementation | "+brand.MCPToolRef("ast", "source")+" |",
		"| Learning how the **external** system behaves | The Hub — "+brand.MCPToolRef("hub", "search")+" for a `knowledge` artifact before model knowledge or web search |",
		"| Running API tests or curl commands | Terminal commands |",
		"| Checking live API responses | Browser or HTTP tools |",
		"",
		"### How to search (step-by-step)",
		"",
		"**Step 1 — Search the wiki (ALWAYS start here)**",
		"  Call "+searchRef+" with your query. The wiki catalogs are grouped by paradigm (REST, gRPC, messaging, etc.).",
		"  Alternatively, call "+browseRef+" for a structured catalog.",
		"  > ⚠️ **Each hit is a title, not the spec.** A search result carries no spec text at all,",
		"  > so a field name, a type, an endpoint path or an error code cannot come from it — open the page",
		"  > with "+wikiSourceRef+", then follow its provenance to the raw spec when exactness matters.",
		"  For deep consultation, search with "+searchRef+", read the returned pages, follow [[wikilinks]] to expand context, call "+xrefsRef+" for cross-references, and synthesize the answer yourself — you ARE the AI.",
		"  For multi-source search (knowledge + memory), call "+wikiSearchRef+" with `wikis: [\"project\", \"memory\"]`.",
		"",
		"**Step 2 — Read frontmatter FIRST**",
		"  Check `confidence`, `type`, `source`, `updated` before reading body content.",
		"  - `confidence < 0.5`: verify against raw spec via provenance link",
		"  - `confidence >= 0.8`: trust the compiled summary",
		"",
		"**Step 3 — Follow [[wikilinks]]**",
		"  Navigate from endpoint → schema → related services via curated links.",
		"",
		"**Step 4 — Expand with cross-references**",
		"  Call "+xrefsRef+" to find every spec that references a given schema or service — pre-computed, zero-cost.",
		"",
		"**Step 5 — Verify via provenance**",
		"  Each page has: `*Provenance: ^[docs/rest/payment.yaml]*`.",
		"  If you need exact field names or raw schemas — ONLY THEN read the original spec.",
		"",
		"### ❌ Anti-patterns (violations of this protocol)",
		"",
		"| Anti-pattern | Why it is a violation |",
		"|---|---|",
		"| `grep -r \"keyword\" docs/` | Brute-force on raw specs; ignores compiled wiki |",
		"| Reading .yaml/.proto files directly without checking wiki first | Skips pre-compiled summary; wastes tokens on raw verbose content |",
		"| Using semantic search to find integration docs | Wiki search is faster and more precise |",
		"| Opening page after page instead of searching | Token bomb; a search returns only what ranked, and the wiki has no files to walk anyway |",
		"| Ignoring cross-references and grepping for `$ref` | Cross-refs are pre-computed; grep is O(n) and misses non-$ref references |",
		"| Guessing API field names from model memory | Model memory is stale; wiki compiles from spec truth |",
		"",
		"### 🔄 Fallback to Built-In Tools — ONLY for Topics the Wiki Does Not Cover",
		"",
		"**Your built-in tools (grep, ripgrep, semantic search, file reading) are permitted",
		"ONLY for topics and domains that the wiki does not cover at all.**",
		"The wiki is ALWAYS your primary source. It is NOT a \"first attempt\" — it is",
		"the definitive source. Your tools exist only for domains outside the wiki's scope.",
		"",
		"Your tools are allowed ONLY when ALL of these conditions are true:",
		"",
		"1. You **already searched the wiki** using "+searchRef+", "+wikiSearchRef+", or "+browseRef+"",
		"2. You **followed relevant [[wikilinks]]** and checked entity pages",
		"3. You **checked cross-references** using "+xrefsRef+" on the most relevant page",
		"4. The wiki **genuinely has no coverage** of the integration (not indexed, not documented)",
		"5. You **state explicitly** to the user: \"The wiki has no coverage of X, falling back to spec search\"",
		"",
		"**If even ONE of these conditions is not met, you MUST NOT use your tools.**",
		"",
		"Examples of valid fallback:",
		"- Wiki has no entity for a newly added external API → read the raw spec file directly",
		"- Wiki entity exists but `confidence < 0.3` → verify against raw spec via provenance link",
		"- Integration was never documented in docs/ → ask the user to document it first",
		"",
		"Examples of INVALID fallback (protocol violations):",
		"- Grepping .yaml files because \"the wiki was slow\" → ❌ wiki is pre-compiled and always faster",
		"- Reading raw proto/graphql without checking wiki first → ❌ wiki has structured summaries",
		"- Using semantic search on docs/ → ❌ wiki search gives structured results",
		"",
		"## Documentation Requirements",
		"",
		"### Mandatory: Use the Correct Format per Paradigm",
		"",
		"| Paradigm | Format | File Extension |",
		"|---|---|---|",
		"| REST APIs | OpenAPI Specification (OAS 3.x) | `.yaml` or `.json` |",
		"| gRPC / High-performance RPC | Protocol Buffers (Protobuf) | `.proto` |",
		"| Messaging / Kafka / Event-driven | AsyncAPI | `.yaml` or `.json` |",
		"| GraphQL | GraphQL SDL (Schema Definition Language) | `.graphql` |",
		"| WebSockets (bidirectional streaming) | AsyncAPI | `.yaml` or `.json` |",
		"| Webhooks (reactive HTTP callbacks) | OpenAPI (callbacks object) | `.yaml` or `.json` |",
		"| SOAP / Legacy Web Services | WSDL | `.xml` |",
		"| OData / ERP APIs (SAP, Dynamics) | CSDL | `.xml` or `.json` |",
		"| File Exchange / Batch / S3 dumps | JSON Schema | `.json` |",
		"",
		"### Quality Requirements",
		"",
		"All integration files MUST:",
		"",
		"- **Strong typing**: no `any`, no `object` without properties, no optional fields without justification",
		"- **Rich comments**: every endpoint, operation, field, and message MUST have a description",
		"- **Concrete examples**: every operation MUST include at least one complete request/response example",
		"- **Error documentation**: all error codes and error response schemas MUST be documented",
		"- **Authentication**: security schemes MUST be documented for every protected endpoint",
		"- **Versioning**: include version information in every specification file",
		"",
		"### REST APIs (OpenAPI)",
		"",
		"```yaml",
		"# integrations/payment-api.yaml",
		"openapi: '3.0.3'",
		"info:",
		"  title: Payment API",
		"  version: '2.1.0'",
		"  description: |",
		"    Processes payment transactions, refunds, and disputes.",
		"    Base URL: https://api.payments.example.com/v2",
		"paths:",
		"  /transactions:",
		"    post:",
		"      operationId: createTransaction",
		"      summary: Create a new payment transaction",
		"      description: Initiates a payment transaction with full idempotency support.",
		"      requestBody:",
		"        required: true",
		"        content:",
		"          application/json:",
		"            schema:",
		"              $ref: '#/components/schemas/CreateTransactionRequest'",
		"            example:",
		"              amount: 9999",
		"              currency: BRL",
		"              customer_id: cust_abc123",
		"              payment_method: card",
		"      responses:",
		"        '201':",
		"          description: Transaction created successfully",
		"          content:",
		"            application/json:",
		"              schema:",
		"                $ref: '#/components/schemas/Transaction'",
		"              example:",
		"                id: txn_xyz789",
		"                status: pending",
		"                amount: 9999",
		"                currency: BRL",
		"        '422':",
		"          description: Validation error",
		"          content:",
		"            application/json:",
		"              schema:",
		"                $ref: '#/components/schemas/ValidationError'",
		"```",
		"",
		"### gRPC (Protobuf)",
		"",
		"```proto",
		"// integrations/user-service.proto",
		"syntax = \"proto3\";",
		"package user.v1;",
		"",
		"// UserService manages user accounts and authentication.",
		"service UserService {",
		"  // GetUser retrieves a user by ID.",
		"  // Returns NOT_FOUND if the user does not exist.",
		"  rpc GetUser(GetUserRequest) returns (GetUserResponse);",
		"",
		"  // ListUsers returns a paginated list of users.",
		"  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);",
		"}",
		"",
		"message GetUserRequest {",
		"  // user_id is the unique identifier (UUID v4).",
		"  string user_id = 1;",
		"}",
		"```",
		"",
		"### Messaging / Kafka (AsyncAPI)",
		"",
		"```yaml",
		"# integrations/order-events.yaml",
		"asyncapi: '2.6.0'",
		"info:",
		"  title: Order Events",
		"  version: '1.0.0'",
		"channels:",
		"  order.created:",
		"    description: Published when a new order is placed.",
		"    publish:",
		"      operationId: onOrderCreated",
		"      message:",
		"        $ref: '#/components/messages/OrderCreated'",
		"components:",
		"  messages:",
		"    OrderCreated:",
		"      name: OrderCreated",
		"      payload:",
		"        $ref: '#/components/schemas/Order'",
		"      examples:",
		"        - payload:",
		"            order_id: ord_abc",
		"            customer_id: cust_123",
		"            total: 15000",
		"```",
		"",
		"### GraphQL (SDL)",
		"",
		"```graphql",
		"# integrations/product-api.graphql",
		"\"\"\"",
		"Product represents a sellable item in the catalog.",
		"\"\"\"",
		"type Product {",
		"  \"\"\"Unique product identifier (ULID)\"\"\"",
		"  id: ID!",
		"  \"\"\"Human-readable product name\"\"\"",
		"  name: String!",
		"  \"\"\"Price in cents (BRL)\"\"\"",
		"  price: Int!",
		"}",
		"",
		"type Query {",
		"  \"\"\"Retrieve a product by ID. Returns null if not found.\"\"\"",
		"  product(id: ID!): Product",
		"}",
		"```",
		"",
		"## Workflow",
		"",
		"**0. (MANDATORY) Before touching any external system:**",
		"   - Call "+hubSearchRef+" with the system's name and `type: \"knowledge\"` — always. "+hubListRef+" cannot filter by name, only by type; it is the fallback when search comes back empty.",
		"   - If found: call "+knowledgeInstallRef+" with `name` and read the wiki.",
		"   - If not found: document what the user provides, never assume.",
		"",
		"1. **Before creating an integration**: check the wiki index to avoid duplication.",
		"2. **When discovering an undocumented integration**: create the spec file immediately.",
		"4. **Never leave an integration undocumented** — treat specs as first-class code artifacts.",
		"5. **Never guess** — if in doubt, stop and ask the user.",
	)
	result := strings.Join(lines, "\n") + "\n"
	if docsDir != "docs" {
		result = strings.ReplaceAll(result, "`docs/", "`"+docsDir+"/")
		result = strings.ReplaceAll(result, "\"docs/", "\""+docsDir+"/")
		result = strings.ReplaceAll(result, " docs/", " "+docsDir+"/")
		result = strings.ReplaceAll(result, "(docs/", "("+docsDir+"/")
		result = strings.ReplaceAll(result, "in `docs/`", "in `"+docsDir+"/`")
	}
	return result
}

var knowledgeSkillName = brand.SkillDirName("knowledge")

func MandateTrigger() string {
	return ide.ModuleMandateTrigger(
		"Knowledge & Documentation",
		knowledgeSkillName,
		"documentation or project-knowledge",
		"The task log OPENS the task and stays current through it: BEFORE you touch anything, create the task log under the docs tasks directory with the objective, your reasoning, the justification for the approach, and the plan broken into tasks — one entry per task, each with its spec. Then update it as each step lands, as the direction changes, and as debt appears, so that another agent can take the work over from the log alone, at any moment, without your conversation. After ANY code change the task log MUST be updated — a change without its record is not complete. The task backlog records future work independently of Dream; Dream never consumes backlog items, because its role is to improve project knowledge. Search the knowledge wiki via MCP tools BEFORE grepping or reading docs directly. Reindexing is NOT your job: the daemon watches the docs tree and rebuilds the wiki on its own — but it lags the write, so when you need certainty that an index is current, call "+brand.MCPToolRef("sync")+" and let it finish.\n"+
			"SEARCH ANSWERS WITH TITLES, NOT WITH PAGES. A search result is a slug, a title, a type and a score — it carries no page text, deliberately, so that the tokens go on the one or two pages you actually decide to open rather than on twenty previews. Choosing is yours: read the titles, pick, then call "+brand.MCPToolRef("wiki", "source")+" on what you picked, with `pattern` or a line range when the page is long. Acting on a search result alone is acting on a title you never read. `preview: true` buys a short excerpt per hit when two titles genuinely do not separate — it is the exception.",
		[]string{
			"you are about to start a task of any size — the task log is the FIRST artifact of it, written before the work, never a report you assemble at the end",
			"you finished a step, changed direction, hit a blocker, or learned something that changes the plan — the log is updated at that moment, not when the task ends",
			"you are resuming after an interruption or after the user asked for changes or corrections — read the existing task log before you touch anything, and re-apply this skill's protocol instead of continuing from what you remember (re-apply it; if you already read the skill this session there is nothing to open again)",
			"you need certainty that what a tool returns is current — the automatic reindex lands after the write, so call " + brand.MCPToolRef("sync") + " and let it finish before you decide anything on the result",
			"you are about to grep, glob, or read files under the docs tree to find something",
			"you are about to open a wiki page as a file — you cannot: the wiki is global and outside your workspace, so " + brand.MCPToolRef("wiki", "source") + " is the only way to read a page",
			"the request asks why something is the way it is — a decision, a constraint, a trade-off already made",
			"the request is about a feature, an architecture, or a specification rather than about a specific symbol",
			"you are about to state how this project works, from inference rather than from something you read here",
			"the task involves an external system integration, an API contract, or a spec",
			"the user asks how a named system works, or whether it has some functionality, and that system is not this project's own code — check the Hub (installed context, then hub_search) before answering",
			"you finished a change and have not yet recorded it",
			"you identified a task that should be recorded for later instead of being lost or forced into the current change",
			"you are about to add, list, or remove an item in the task backlog — Dream state is irrelevant to these operations",
			"you need the provenance of a page — what links to it, what it came from",
			"a search returned nothing and you cannot tell whether the page is missing or just ranked low",
			"a search came back and you are about to act on it — you cannot: " + brand.MCPToolRef("knowledge", "search") + " answers with TITLES, so pick the one or two the titles justify and read them with " + brand.MCPToolRef("wiki", "source") + " before you conclude anything",
			"an index looks stale, or a graph read failed to open the database — find out whether the daemon is alive before concluding anything",
			"the documentation you need belongs to another project — resolve it in the ecosystem and search ITS wiki, never walk or grep its docs tree",
		},
		[]string{"knowledge_search", "wiki_search", "wiki_browse", "wiki_xrefs", "wiki_log", "wiki_source", "wiki_embed", "knowledge_list", "knowledge_lint", "knowledge_schema", "knowledge_export", "knowledge_install", "knowledge_remove", "knowledge_sync", "backlog_list", "backlog_add", "backlog_remove", "cluster_projects", "daemon_status", "daemon_stop"},
	)
}

func resolveDocsDirFromProject(projectDir string) string {
	lp := filepath.Join(projectDir, brand.LockFileName())
	var projectCfg config.ConfigMap
	if lf, err := hub.LoadLockfile(lp); err == nil && lf != nil {
		projectCfg = lf.Config
	}
	return config.ResolveDocsDir(nil, projectCfg)
}

func InstallRule(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}

	if err := ide.UpsertMandateTrigger(projectDir, ideName, "doc_rule", MandateTrigger()); err != nil {
		return err
	}

	return InstallSkill(projectDir, ideName)
}

func InstallSkill(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	docsDir := resolveDocsDirFromProject(projectDir)
	contexts := InstalledContextsIn(projectDir)
	skillContent := brand.ResolveModuleSkill("knowledge", KnowledgeRuleContent(contexts, docsDir))
	descDocsRef := docsDir + "/"
	frontmatter, err := ide.SkillFrontmatter(knowledgeSkillName, "Manages project documentation, knowledge wiki, and integration specs. MANDATORY: After ANY code change, create/update the task log in "+descDocsRef+"tasks/ — reindexing is automatic, the daemon watches the docs tree. Search the knowledge wiki BEFORE grepping documentation files. Use when: understanding project features, architecture, decisions, or specifications; creating or updating documentation; working with external system integrations or API specs; searching for project knowledge, backlinks, or provenance; discovering or documenting undocumented integrations.")
	if err != nil {
		return err
	}
	return ide.InstallManagedSkill(projectDir, ideName, knowledgeSkillName, frontmatter+skillContent)
}

func RemoveRule(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}

	return ide.RemoveMandateTrigger(projectDir, ideName, "doc_rule")
}

func RemoveSkill(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	return ide.RemoveManagedSkill(projectDir, ideName, knowledgeSkillName)
}
