package memory

import (
	"os"
	"strings"

	"github.com/graphit-labs/graphit-code/internal/brand"
	"github.com/graphit-labs/graphit-code/internal/hub/adapters/ide"
)

func RuleContent(contexts []string) string {
	_ = contexts // contexts are managed by the wiki DB; callers may pass them but they're not used in the rule text
	displayName := brand.DisplayName

	memInsertRef := brand.MCPToolRef("memory", "insert")
	memInsert := brand.MCPToolName("memory", "insert")
	memDelete := brand.MCPToolName("memory", "delete")
	memDeleteRef := brand.MCPToolRef("memory", "delete")
	memUpdate := brand.MCPToolName("memory", "update")
	memSearch := brand.MCPToolName("memory", "search")
	memSearchRef := brand.MCPToolRef("memory", "search")

	memPromote := brand.MCPToolName("memory", "promote")
	memDemote := brand.MCPToolName("memory", "demote")
	memList := brand.MCPToolName("memory", "list")
	memImportant := brand.MCPToolName("memory", "important")

	wikiSourceRef := brand.MCPToolRef("wiki", "source")
	wikiSource := brand.MCPToolName("wiki", "source")
	memIndexRef := brand.MCPToolRef("memory", "index")
	memExport := brand.MCPToolName("memory", "export")
	memExportRef := brand.MCPToolRef("memory", "export")
	memSchema := brand.MCPToolName("memory", "schema")
	memSchemaRef := brand.MCPToolRef("memory", "schema")
	memRemove := brand.MCPToolName("memory", "remove")
	memSyncTool := brand.MCPToolName("memory", "sync")
	memWildcard := "`" + brand.Brand + "_memory_*`"

	lines := []string{
		"# Memory Management Rule",
		"",
		"> This rule is auto-managed by " + displayName + ". Do not edit this block manually.",
		"",
		"## 🚨 SESSION START PROTOCOL — Execute BEFORE Any Response",
		"",
		"**These steps are MANDATORY. Execute them BEFORE responding to the user's first message.**",
		"**Skipping them means you WILL repeat mistakes the user already corrected.**",
		"",
		"1. Call " + memSearchRef + " with context from the user's request to find relevant memories",
		"2. If relevant memories found, read the entity page(s) and follow their guidance",
		"3. Only then proceed with the user's request",
		"",
		"> If the memory wiki does not exist yet (new project), skip and proceed.",
		"",
		"> **An empty search result does not tell you which of the two you are in** — a store with",
		"> nothing in it and a store where nothing matched your words look identical, and guessing",
		"> wrong costs a second and third search on a base that was never going to answer.",
		"> `" + brand.MCPToolName("memory_list") + "` settles it in ONE call: it reads the store",
		"> directly rather than the compiled wiki, so an empty listing means the store really is",
		"> empty — cold start, nothing to recall, proceed — while a populated one means your query",
		"> missed and rewording is worth it. Reach for it the first time a search comes back empty,",
		"> not after the third.",
		"",
	}

	lines = append(lines,
		"",
		"## 📖 When to Read Memory (Beyond Session Start)",
		"",
		"**Memory reading is NOT limited to session start.** You MUST also consult memory",
		"in these situations — proactively, without being asked:",
		"",
		"| Situation | What to search for | Why |",
		"|---|---|---|",
		"| **Before implementing** any significant change | Conventions, decisions, constraints about affected modules | Avoid violating established patterns or repeating rejected approaches |",
		"| **When stuck** or your approach isn't working (2+ failed attempts) | Skills, workarounds, corrections related to the problem | The solution may already exist — you may be repeating a known mistake |",
		"| **Non-obvious error** or unexpected behavior | Facts, skills, debugging steps about the affected area | Someone (you or another agent) may have debugged this before |",
		"| **Trying to understand** \"why is it done this way?\" | Decisions, tensions, facts about the module/pattern | The rationale is captured in memory — don't guess |",
		"| **Multiple attempts failing** (3+ tries on same problem) | Corrections, skills, workarounds | STOP and read before trying again — you are likely repeating a known error |",
		"| **Before proposing** architecture or technical approach | Decisions, tensions, conventions that constrain options | Avoid contradicting prior decisions the user already made |",
		"| **User seems frustrated** or repeats an instruction | Corrections about your behavior | You may be ignoring a correction already memorized |",
		"",
		"**How to search:** call "+memSearchRef+" tool (passing absolute `project_dir` parameter)",
		"",
		"### Another project's memories are readable too",
		"",
		"`project_dir` is not fixed to the project you are sitting in. When the work touches a sibling",
		"project in the ecosystem, **its** memories are where its conventions, corrections and",
		"trade-offs live:",
		"",
		"```",
		brand.MCPToolName("cluster", "projects")+"(project_dir: \"/path/to/project\")   # get the sibling's dir",
		memSearch+"(project_dir: \"<sibling dir>\", query: \"<what you are about to change or assume>\")",
		"```",
		"",
		"Do this before changing anything over there, and before explaining why it behaves as it does.",
		"Its code shows *what*; its memories are the only record of *why*, and reading the source will",
		"not reconstruct a decision someone made deliberately.",
		"",
		"### And with no project at all, memory still works",
		"",
		"**`project_dir` is optional on every memory tool that reads or writes a scope** — search,",
		"list, important, insert, update, delete, promote, demote, index. Omitting it serves the **user**",
		"scope, which is keyed by this machine rather than by a project, so it is a real scope and not a",
		"consolation prize:",
		"",
		"```",
		memSearch+"(query: \"<what you are about to assume>\")",
		memInsert+"(title: \"<title>\", content: \"<body>\")",
		brand.MCPToolName("wiki", "source")+"(path: \"<slug>\", wiki: \"memory\")",
		"```",
		"",
		"This is for the caller that has no checkout to name — an agent reaching this server over HTTP.",
		"Two things to know:",
		"",
		"- **A request for the `project` scope with no `project_dir` is served from the user scope, and",
		"  the answer says so.** A project scope is keyed by a project identity; there is none. It is a",
		"  redirect rather than a refusal because the session-start search happens before an agent knows",
		"  whether it has a project, and failing that call would lose whatever it was about to record.",
		"- **`"+memExport+"`, and the imported-context tools, still need a project.** They act on the",
		"  project memory store, which does not exist without one.",
		"",
		"## 🔒 This Framework IS Your Memory — No Other Exists",
		"",
		"- **ALWAYS** use the "+memInsertRef+" tool (passing absolute `project_dir` parameter) to persist facts across sessions.",
		"- **NEVER** use IDE-native memory, model memory, or any built-in \"remember\" feature.",
		"- **ALWAYS** read the memory wiki to recall — never rely on what you \"think you know\".",
		"- This applies to ALL persistent facts: conventions, corrections, decisions, preferences.",
		"",
		"## 🔒 MANDATORY: Memory MCP Tools REPLACE Your Native Recall",
		"",
		"> **The "+brand.Brand+" memory MCP tools are your PRIMARY and ONLY mechanism for",
		"> persisting and recalling knowledge across sessions.** They take ABSOLUTE",
		"> PRECEDENCE over any built-in/native memory, recall, or \"remember\" feature of",
		"> your model or IDE. Use them via MCP ONLY — NEVER via the CLI, and NEVER",
		"> substitute them with your own recall.",
		"",
		"### Why this replaces your tools",
		"",
		"| Your tool | Memory MCP equivalent | Why the MCP tool wins |",
		"|---|---|---|",
		"| Model/native \"memory\" or recall | Call "+memSearchRef+", then read the wiki page | Native memory is ephemeral and per-session; the wiki survives across sessions and agents |",
		"| Remembering facts \"in your head\" | Call "+memInsertRef+" to persist | Your context is wiped between sessions — unpersisted knowledge is lost |",
		"| `grep`/ripgrep over memory files | Call "+memSearchRef+" | BM25-ranked over the compiled wiki (~200 tokens) vs scanning anything |",
		"| Reading every memory to find one | Call "+memSearchRef+" or `"+memList+"` | Search ranks and answers with titles; listing reads the store. Opening pages one by one is the cost both exist to avoid |",
		"| Opening a memory page with your file-read tool | Call "+wikiSourceRef+" with `wiki: \"memory\"` | Takes the project as a parameter, so it reaches memories outside your workspace — and slices a long memory down to the part you asked for |",
		"",
		"### 🔒 When you MUST use the memory MCP tools (MANDATORY — no exceptions)",
		"",
		"| Scenario | What to do | What NOT to do |",
		"|---|---|---|",
		"| **Recalling any project knowledge** | Call "+memSearchRef+" → read the page | ❌ Don't answer from model memory or guess |",
		"| **Persisting a fact/decision/correction** | Call "+memInsertRef+" | ❌ Don't rely on native/model memory to \"remember\" |",
		"| **Listing what is known** | Call `"+memList+"` / `"+memImportant+"` | ❌ Don't `ls`/read the memory directory |",
		"| **Replacing an outdated memory** | Call `"+memUpdate+"` to rewrite it in place | ❌ Don't edit `.md` files directly, and don't delete-then-insert — that loses the id, importance and tags |",
		"",
		"### 🔄 Fallback — There Is NO Fallback for Memory",
		"",
		"There is **no built-in alternative** to this framework's memory. You MUST NOT use",
		"model-native memory, IDE memory, or any external scratchpad. The ONLY acceptable",
		"action when the memory MCP tools are genuinely unavailable is to state explicitly",
		"to the user: \"The memory MCP tools are unavailable, so I cannot persist/recall this now.\"",
		"",
		"### ❌ Anti-patterns (violations of this protocol)",
		"",
		"| Anti-pattern | Why it is a violation |",
		"|---|---|",
		"| Answering project questions from model memory | Model memory is stale/ephemeral; the wiki is the source of truth |",
		"| Using the CLI (`"+brand.Brand+" memory ...`) instead of MCP tools | Agent-facing work MUST go through MCP tools, never the CLI |",
		"| `grep`-ing raw `.md` memory files | Bypasses BM25 ranking and compiled summaries; wastes tokens |",
		"| Saying \"I'll remember that\" without calling "+memInsertRef+" | The knowledge is lost at session end — it was never persisted |",
		"",
		"## 🎯 Trigger → Action Table",
		"",
		"**When you observe a trigger, execute the corresponding action immediately.**",
		"**Do NOT ask for permission. Do NOT skip. Confirm with: \"Done, I've memorized: <title>\"**",
		"",
		"### 💾 Save Triggers — Memorize Immediately",
		"",
		"**Every memory MUST follow the structured content template below (What/Why/How/Impact).**",
		"This ensures memories are complete and actionable across sessions.",
		"",
		"#### 📝 Memory Content Template",
		"",
		"When creating a memory, always include these four fields in the `content` parameter:",
		"",
		"```",
		"What: <what was done or what happened>",
		"Why: <why it was done — the motivation, root cause, or user intent>",
		"How: <how it was resolved — the approach, steps taken, or implementation>",
		"Impact: <how it impacted the system — side effects, files changed, behavior changes>",
		"```",
		"",
		"#### Trigger Table",
		"",
		"| You observe... | Action | Tool Call (always pass absolute `project_dir` parameter) |",
		"|---|---|---|",
		"| User says \"always/never/prefer/avoid/must\" about code | Store as convention | "+memInsertRef+" with `title: \"<rule>\"`, `type: \"convention\"`, `important: true` |",
		"| User corrects your behavior or approach | Store the correction | "+memInsertRef+" with `title: \"<correction>\"`, `type: \"correction\"`, `important: true`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User **gives any instruction or directive** (even without \"always/never\") | **Evaluate for memory** — determine if it contains a convention, preference, correction, fact, or skill worth persisting. If yes, memorize it with the appropriate type. NEVER just say \"understood\" or confirm comprehension without evaluating. | "+memInsertRef+" with appropriate `type` if the instruction is worth persisting |",
		"| User **guides, orients, or gives direction** on how to proceed | Store the guidance | "+memInsertRef+" with `title: \"<guidance>\"`, `type: \"convention\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User **intervenes** mid-task to change course or redirect | Store the intervention as correction | "+memInsertRef+" with `title: \"<intervention>\"`, `type: \"correction\"`, `important: true`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User gives a **tip, hint, or suggestion** on how to do something | Store as skill | "+memInsertRef+" with `title: \"<tip>\"`, `type: \"skill\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User **explains how something works** or why it's done a certain way | Store as fact | "+memInsertRef+" with `title: \"<knowledge>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User **shows you a workflow** or operational procedure (e.g., \"run make install first\") | Store as skill | "+memInsertRef+" with `title: \"<procedure>\"`, `type: \"skill\"`, `important: true`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User **repeats an instruction** they already gave (frustration signal) | Store as correction | "+memInsertRef+" with `title: \"<what you missed>\"`, `type: \"correction\"`, `important: true`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **complete a task** (new feature, refactor, or significant change) | Record what was done | "+memInsertRef+" with `title: \"<task summary>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **modify an existing feature** (behavior change, extension, or rework) | Record the modification | "+memInsertRef+" with `title: \"<feature> modified: <summary>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **fix a bug** | Record the bug fix | "+memInsertRef+" with `title: \"Bug fix: <summary>\"`, `type: \"skill\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You make an architectural/design choice | Record the decision | "+memInsertRef+" with `title: \"<decision>\"`, `type: \"decision\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You chose X over Y with explicit trade-offs | Capture the tension | "+memInsertRef+" with `title: \"<choice>\"`, `type: \"tension\"`, `content: \"Chose: X\\nOver: Y\\nBecause: ...\\nAccepting: ...\\nImpact: ...\"` |",
		"| You **discover something unexpected** during investigation | Store the discovery | "+memInsertRef+" with `title: \"<discovery>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You find a **workaround or creative solution** to a problem | Store the workaround | "+memInsertRef+" with `title: \"<workaround>\"`, `type: \"skill\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You make a **non-obvious inference** that proves correct | Store the inference | "+memInsertRef+" with `title: \"<inference>\"`, `type: \"skill\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **solve a complicated multi-step problem** | Store the full solution | "+memInsertRef+" with `title: \"<problem → solution>\"`, `type: \"skill\"`, `important: true`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You debug a non-obvious issue successfully | Save as a skill | "+memInsertRef+" with `title: \"<solution>\"`, `type: \"skill\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| User reveals a non-obvious project fact | Store the fact | "+memInsertRef+" with `title: \"<fact>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **analyze or reason about how the system works** — while reading code, tracing call flows, or understanding a module | Store the insight immediately | "+memInsertRef+" with `title: \"<insight about system>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **read code and infer a non-obvious pattern, convention, or architectural principle** | Store it as a fact | "+memInsertRef+" with `title: \"<pattern/principle>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **understand why something is implemented a certain way** (even without the user explaining it) | Store as a decision or fact | "+memInsertRef+" with `title: \"<why X is done Y way>\"`, `type: \"decision\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| You **investigate a non-obvious behavior, side effect, or dependency** and understand it | Store the finding | "+memInsertRef+" with `title: \"<behavior/dependency understood>\"`, `type: \"fact\"`, `content: \"What: ...\\nWhy: ...\\nHow: ...\\nImpact: ...\"` |",
		"| New instruction contradicts existing memory | Update it in place to the new truth | `"+memUpdate+"` with `id: \"<old-id>\"`, `content: \"<new truth>\"` |",
		"| **Two memories you just read disagree** | Resolve it now — see Sanitise On Sight | `"+memUpdate+"` the true one, then "+memDeleteRef+" the outdated one |",
		"| **Two memories you just read say the same thing** | Fold them now — union into one, then delete the other | `"+memUpdate+"` then "+memDeleteRef+" |",
		"| **A memory you just read is out of date** (renamed path, removed flag, changed API) | Correct it now, in the same turn | `"+memUpdate+"` with `id: \"<id>\"`, `content: \"<current truth>\"` |",
		"| Memory is still relevant but vague or incomplete | Extend it in place rather than adding a second one | `"+memUpdate+"` with `id: \"<id>\"`, `content: \"<fuller>\"` |",
		"",
		"### 📖 Read Triggers — Consult Memory Before Acting",
		"",
		"| You observe... | Action | What to search for |",
		"|---|---|---|",
		"| You're about to **implement a significant change** | Read memory BEFORE coding | Constraints, conventions, decisions about affected modules |",
		"| You're **stuck or your approach isn't working** (2+ failed attempts) | Read memory for past solutions | Skills, workarounds, debugging steps related to the problem |",
		"| You encounter a **non-obvious error or behavior** | Read memory for known issues | The problem may have been solved before — check skills and facts |",
		"| You need to understand **project context or \"why\"** | Read memory for institutional knowledge | Decisions, tensions, and facts about the area you're working on |",
		"| **Multiple attempts have failed** (3+ tries on same problem) | STOP and read memory | You may be repeating a known mistake — check corrections and skills |",
		"| You're about to **propose architecture or an approach** | Read memory for prior decisions | Decisions, tensions, conventions that constrain options |",
		"| Build/test fails unexpectedly | Check memory for known issues | Read wiki for past debugging skills |",
		"",
		"## 📁 Memory Types",
		"",
		"Every memory has a `type` that determines how it is stored and surfaced:",
		"",
		"| Type | When to use | Typical importance |",
		"|---|---|---|",
		"| `convention` | Coding standards, style patterns, project rules | ✅ important |",
		"| `correction` | User corrected your behavior — never repeat the mistake | ✅ important |",
		"| `decision` | Architectural or design decisions with rationale | depends |",
		"| `tension` | Trade-off choices: chose X over Y because Z, accepting W | depends |",
		"| `fact` | Non-obvious project facts, environment details | rarely |",
		"| `skill` | Debugged workflows, reusable solution patterns | rarely |",
		"",
		"Default type when `type` is omitted: `fact`.",
		"",
		"## 📖 How to Retrieve Memories",
		"",
		"**ALWAYS use the MCP tools.** The wiki is compiled, BM25-indexed and pre-optimized for",
		"retrieval, and it is the only thing there is to read: a memory is a row, not a file you",
		"could open instead. Searching costs a fraction of what walking the store would, and it is",
		"ranked — which walking never is.",
		"",
		"### 🔒 There is no memory directory, in the project or anywhere else",
		"",
		"A memory scope has exactly two artifacts, and NEITHER is a directory of files you could read:",
		"",
		"```",
		"s3://<bucket>/<prefix>/memory/<scope>/<id>   the Lance table — THE TRUTH, when a bucket is configured",
		"<global>/memory-table/memory-<scope>-<id>/   the Lance table — the truth, when there is not",
		"<global>/wiki/memory/<scope>/<id>/           the compiled wiki — what search opens",
		"```",
		"",
		"A memory is a ROW. Its superseded revisions are rows too — `revision_id` and `superseded` are",
		"columns — so there is no `history/` directory either. There used to be a markdown store under",
		"`<global>/memory-raw/`, and a replica of the wiki inside every project that read it. Both are",
		"gone, along with the fan-out that kept the copies in step. So `"+brand.DotDir()+"/memory` does",
		"not exist, and neither does a file you could open.",
		"",
		"This is why "+wikiSourceRef+" is not the *preferred* way to read a memory but the **only**",
		"one — and why it takes `project_dir` as a parameter, which is also what lets it serve a",
		"sibling project's memories.",
		"",
		"**Scope parameter:** `scope: \"project\"` (default) = project-specific memories. `scope: \"user\"` = personal cross-project memories.",
		"",
		"**What "+memSearchRef+" actually searches:** the **compiled memory wiki** — its BM25 index,",
		"and nothing else. There is no second path: it does **not** scan raw files, which is the whole",
		"reason it is ranked and cheap — and the reason a memory written seconds ago may not surface",
		"yet: it is written, but the wiki has not recompiled. When you know something was just written",
		"and search misses it, that is the explanation; "+memIndexRef+" forces the rebuild.",
		"",
		"| What you need | MCP tool | Why |",
		"|---|---|---|",
		"| Search memories by keyword/context | "+memSearchRef+" | Ranked over the compiled wiki — and it answers with TITLES, not with memory text |",
		"| List all memories | `"+memList+"` | Structured catalog, grouped by type — reads the store, so it sees writes the wiki has not compiled yet |",
		"| List important memories only | `"+memImportant+"` | High-priority conventions, corrections |",
	)

	lines = append(lines,
		"",
		"**Retrieval steps:**",
		"1. Call "+memSearchRef+" with query context — get ranked results",
		"   > ⚠️ **What comes back is a LIST OF TITLES, not memories.** Each hit is a slug, a title,",
		"   > a type and a score. There is no memory text in it, by design: a search exists so you",
		"   > can decide WHICH memory to open, and that decision is made on the title. Reading is",
		"   > step 3, and it is a decision you make per memory, not something the search does for",
		"   > you on all twenty hits at once.",
		"   > Two consequences, and neither is optional:",
		"   > **you cannot answer from a search result** — it contains no content to answer from; and",
		"   > **you should not open every hit** — pick the one or two the titles justify, read those,",
		"   > and search again with better words if they were the wrong ones.",
		"   > When the titles genuinely do not separate two candidates, pass `preview: true` for a",
		"   > short excerpt per hit. That is the exception, not the default, and it costs tokens on",
		"   > every hit including the ones you will never open.",
		"2. If results reference related memories, call "+memSearchRef+" again with refined query",
		"3. **Read the memory you picked** with "+wikiSourceRef+" — `wiki: \"memory\"` — then follow its",
		"   links and synthesize the answer yourself. This step is not optional: it is where the",
		"   content comes from. It slices, so a long memory costs you the part you asked for:",
		"   ```",
		"   "+wikiSource+"(project_dir: \"/path/to/project\", path: \"<slug from search>\", wiki: \"memory\")",
		"",
		"   # only the part that matters, on a long memory",
		"   "+wikiSource+"(project_dir: \"/path/to/project\", path: \"<slug>\", wiki: \"memory\", pattern: \"<term>\", before: 2, after: 4)",
		"",
		"   # a sibling project's memory — a file read cannot reach outside your workspace",
		"   "+wikiSource+"(project_dir: \"<sibling dir>\", path: \"<slug>\", wiki: \"memory\")",
		"   ```",
		"   For the catalogue rather than one page, "+brand.MCPToolRef("wiki", "browse")+" with `wiki: \"memory\"`.",
		"4. **Never** try to read a memory `.md` file or grep the memory store — there is no copy in",
		"   the project and the global store is outside your workspace. "+wikiSourceRef+" is how a",
		"   memory gets read, for this project and for any other.",
		"",
		"## 🕓 A Memory Has a History, and You Can Read It",
		"",
		"An update does not overwrite the past. It rewrites the memory in place — same id, so",
		"everything that referred to it still resolves — and files the version being replaced under",
		"`history/<id>/<revision>.md`. Every one of those revisions is compiled into the wiki and is",
		"**searchable and readable exactly like a live memory**. Nothing is lost when a memory is",
		"corrected; it moves one step back in a chain you can walk.",
		"",
		"The chain is doubly linked, and both links are in the frontmatter:",
		"",
		"| Field | On | Meaning |",
		"|---|---|---|",
		"| `previous` | any revision after the first | the version this one replaced — **follow it to go back in time** |",
		"| `next` | superseded revisions only | the version that replaced this one; `<id>.md` when that is the live memory |",
		"| `revision` | everything | how many writes this memory has had, starting at 1 |",
		"| `revision_id` | superseded revisions only | this revision's own address inside the chain |",
		"| `updated_by` | everything | the unit that made the last write — **not** a pointer, it is the author |",
		"",
		"`previous` and `next` are the chain; `revision` counts it; `updated_by` is who, and is a",
		"different question entirely. A live memory has no `next`, and that absence is its",
		"definition: it is the head.",
		"",
		"### What this changes about reading a search result",
		"",
		"**Two revisions of one memory never both appear in your results.** When a query matches the",
		"current version and an old one, only the current is returned, with no mention of the old —",
		"because `previous` and `next` make the two provably one memory, and one memory has no",
		"business occupying two of your result slots. You do not have to notice this or work around",
		"it; it is done before the answer reaches you.",
		"",
		"**What you WILL see is a hit that is only an old revision**, and it looks like this:",
		"",
		"```",
		"results[2]{slug|title|type|score|superseded|current}:",
		"  Some_current_memory|Some current memory|fact|61.2|-|-",
		"  An_older_wording--r01M1F…|An older wording|fact|48.9|yes|01M0CWRQ6VBRTPQBTK6T4ZNW3G",
		"```",
		"",
		"A row with `superseded=yes` matched text the project has since changed its mind about, and",
		"`current` is the id of what it believes now. **The decision is yours and it is a real one:**",
		"",
		"- the old wording is what answered your query, so it is often exactly what you want — a",
		"  measurement taken under an architecture that no longer exists, the phrasing of a decision",
		"  before it was revised, the reason something used to be done differently",
		"- but do not act on it as current. Read the `current` memory before you conclude anything",
		"  about how the system behaves **today**",
		"- and when the two disagree in a way that matters, that is not a contradiction to resolve —",
		"  see Sanitise On Sight, which is about two LIVE memories. A superseded revision is supposed",
		"  to disagree with its successor. That is what it is for",
		"",
		"### Walking the chain",
		"",
		"A revision page is read like any other page — the slug is what search gave you:",
		"",
		"```",
		"# the revision that matched",
		""+wikiSource+"(project_dir: \"/path/to/project\", path: \"<slug from search>\", wiki: \"memory\")",
		"",
		"# what it says it replaced, and what replaced it: read `previous` / `next` off that page",
		""+wikiSource+"(project_dir: \"/path/to/project\", path: \"<slug>\", wiki: \"memory\", pattern: \"previous\", after: 1)",
		"```",
		"",
		"Use it when the question is **how something came to be the way it is**: what a memory said",
		"before the correction, when the belief changed, and what it was replaced with. That is a",
		"question the current memory alone cannot answer, and until now the answer was unreachable.",
		"",
		"## 📋 MCP Tools Reference",
		"",
		"All memory actions must be executed via the corresponding MCP tools. Always pass the absolute `project_dir` parameter.",
		"",
		"```",
		"# Insert (default: project scope, type: fact)",
		memInsert+"(project_dir: \"/path/to/project\", title: \"<title>\", content: \"<body>\", type: \"<type>\")",
		"",
		"# Insert important convention",
		memInsert+"(project_dir: \"/path/to/project\", title: \"<title>\", content: \"<body>\", type: \"convention\", important: true)",
		"",
		"# Insert correction",
		memInsert+"(project_dir: \"/path/to/project\", title: \"<title>\", content: \"<body>\", type: \"correction\", important: true)",
		"",
		"# Insert with tags",
		memInsert+"(project_dir: \"/path/to/project\", title: \"<title>\", content: \"<body>\", tags: \"auth,security\")",
		"",
		"# Insert user-scoped memory",
		memInsert+"(project_dir: \"/path/to/project\", title: \"<title>\", content: \"<body>\", scope: \"user\")",
		"",
		"# Update existing memory",
		memUpdate+"(project_dir: \"/path/to/project\", id: \"<id>\", content: \"<new body>\")",
		"",
		"# Delete",
		memDelete+"(project_dir: \"/path/to/project\", id: \"<id>\")",
		"",
		"# Search (lightweight, no AI)",
		memSearch+"(project_dir: \"/path/to/project\", query: \"<term>\")",
		"",
		"# Promote/demote importance",
		memPromote+"(project_dir: \"/path/to/project\", id: \"<id>\")",
		memDemote+"(project_dir: \"/path/to/project\", id: \"<id>\")",
		"",
		"# List all",
		memList+"(project_dir: \"/path/to/project\")",
		memImportant+"(project_dir: \"/path/to/project\")",
		"",
		"```",
		"",
		"> There is no consolidation tool, and no garbage collection tool. Resolving",
		"> duplicates, contradictions and outdated memories is done with the tools above —",
		"> `"+memUpdate+"` and "+memDeleteRef+" — at the moment you notice them. See",
		"> **Sanitise On Sight** below.",
		"",
		"## 🧹 Sanitise On Sight — Your Job, Not a Maintenance Window's",
		"",
		"**You fix the memory store while you are in it.** Whenever you read memories and notice one",
		"of the four problems below, resolve it in the same turn — before continuing with whatever",
		"you were doing. Do not collect these into a list for later, do not report them as findings,",
		"and do not wait to be asked.",
		"",
		"| What you notice | What you do | Tool |",
		"|---|---|---|",
		"| **Two memories say the same thing** | Fold them into one: write the union of both into the better-written one, then delete the other. Union, not summary — keep every distinct fact, path, number and caveat from both. | "+memUpdate+" then "+memDeleteRef+" |",
		"| **Two memories contradict** | Determine which is true NOW. Update it to state the current truth, and keep the superseded claim as history when the *fact that it changed* is itself useful. Then delete the outdated one. | "+memUpdate+" then "+memDeleteRef+" |",
		"| **A memory is deprecated** — it describes an API, path, flag or workflow that no longer exists | Update it to describe what is true now. If the old behaviour explains why the new one looks odd, say so in the same memory. | `"+memUpdate+"` |",
		"| **A memory is right but incomplete or vague** | Extend it in place. A second memory beside it makes both harder to find. | `"+memUpdate+"` |",
		"",
		"### The one rule about deleting",
		"",
		"**Carry the content forward first.** Write the surviving memory, verify it holds everything",
		"worth keeping, and only then delete the other. Reversed, an interruption between the two",
		"steps loses the knowledge permanently; in this order the worst case is a duplicate that",
		"survives until someone notices it again.",
		"",
		"Never delete a memory whose knowledge exists nowhere else. \"Old\", \"narrow\" and \"I did not",
		"need it this time\" are not reasons — they describe most of the memories that later save a",
		"session.",
		"",
		"### Why this is yours and not a scheduled job",
		"",
		"You have what a scheduled pass does not: the reason you were reading those memories. You know",
		"which one matched the task, which one misled you, and which one the code has since outgrown.",
		"A background pass sees text without that context and has to be conservative.",
		"",
		"The "+brand.DisplayName+" dream module does run a scheduled consolidation over the whole store,",
		"and it is deliberately narrow: it merges what it can prove is duplicated, resolves what it can",
		"prove contradicts, refuses anything it cannot carry forward safely, and writes every refusal",
		"into its report. The refusals are the work left for an agent with context — you. The two are",
		"complements, so finding something does not mean waiting for the other one to get to it.",
		"",
		"## 🗄️ The Remaining Tools",
		"",
		"### "+memExportRef+" — push project memories to the git repository",
		"",
		"```",
		memExport+"(project_dir: \"/path/to/project\")",
		"```",
		"",
		"Reindexes, then syncs the project memory store back to its local git repository. Memories",
		"already persist to disk on "+memInsertRef+" — this is the step that makes them **shareable**,",
		"so it matters when the user says another machine or another agent should see them. Project",
		"scope only; there is no `scope` parameter.",
		"",
		"### "+memSchemaRef+" — the shape of the memory graph",
		"",
		"```",
		memSchema+"(project_dir: \"/path/to/project\")",
		"```",
		"",
		"Node labels (`Document`, `Section`), edges (`REFERENCES`, `CONTAINS`) and the properties on",
		"each. Read it before you assume a field exists on a memory page. It is fixed text, not a",
		"live introspection of your data — an empty store returns the same answer as a full one.",
		"",
		"### Imported memory contexts",
		"",
		"When a Hub artifact or another repository brings its own memories along, they arrive as a",
		"named context beside your own:",
		"",
		"```",
		"# Pull that context's memories in again after it changed upstream",
		memSyncTool+"(project_dir: \"/path/to/project\", context: \"<name>\")",
		"",
		"# Drop the context — removes the link, not your own memories",
		memRemove+"(project_dir: \"/path/to/project\", context: \"<name>\")",
		"```",
		"",
		"`context` is **required** on both. Neither touches project or user scope, so neither is a",
		"way to delete a memory — that is "+memDeleteRef+" with an `id`.",
		"",
		"## 🔄 Contradiction Protocol",
		"",
		"When the user's new instruction contradicts an existing memory:",
		"",
		"1. Find the contradicted memory with "+memSearchRef+" and read the page",
		"2. Write the new truth into it: call `"+memUpdate+"` with the corrected content —",
		"   updating in place keeps the memory's id, type, importance and tags, so anything that",
		"   already referred to it still resolves",
		"3. Only if the old memory is about something that no longer exists at all, delete it with",
		"   "+memDeleteRef+" **after** the replacement knowledge is written somewhere",
		"4. Confirm: \"Updated memory: '<title>' now records <the new truth>\"",
		"",
		"> Delete-then-insert also works, and used to be the instruction here, but it loses the id,",
		"> the importance flag and the tags, and it has a window where the knowledge exists nowhere.",
		"> Prefer updating in place.",
		"",
		"## 📣 Transparency Rules",
		"",
		"- **Never** ask permission to create memories — just save silently.",
		"",
		"## ⚡ Reindex After Writes — automatic, but not instant",
		"",
		"After any write (`insert`, `delete`, `update`, `promote`, `demote`), the auto-cycle",
		"runs automatically. If it fails, trigger manually calling the "+memIndexRef+" tool (passing absolute `project_dir` parameter).",
		"",
		"**\"Automatic\" means eventually, not immediately.** The recompile lands after the write, so",
		"there is a short window in which the memory exists in the store and "+memSearchRef+" still",
		"cannot see it — and search does not report the gap, it just answers from the previous state.",
		"Two consequences worth acting on:",
		"",
		"- **`"+memList+"` reads the store, not the wiki.** When you need to confirm that something you",
		"  just wrote is really there, list rather than search — that is the read that cannot be behind.",
		"- **When you need CERTAINTY that the indexes are current — before deciding on what they",
		"  return, or before reporting work as done — call it, do not assume it.** "+memIndexRef+" rebuilds",
		"  the memory wiki alone; "+brand.MCPToolRef("sync")+" is what brings the memory wikis, the",
		"  knowledge wiki and the AST graph to the same point, which is what makes \"up to date\" a fact",
		"  you established instead of one you hoped for.",
		"",
		"## ⛔ Critical Rules (Never Violate)",
		"",
		"1. **Read memory at session start.** Your context lives there. Skipping = repeating mistakes.",
		"2. **Never leave a correction un-memorized.** If the user corrects you, save it immediately.",
		"3. **Never edit .md memory files directly.** Always use "+memWildcard+" MCP tools.",
		"4. **Capture trade-offs, not just facts.** \"We chose X over Y because Z\" > \"We use X\".",
		"5. **Handle contradictions when you see them.** Update the memory that is true; never leave two conflicting memories behind for a later session to trip over. Same for duplicates and for memories the codebase has outgrown — fixing them is part of reading them, not separate work.",
		"6. **Promote critical memories.** Conventions, corrections, and constraints should be marked important.",
		"7. **NEVER just say \"understood\" or confirm comprehension.** When the user gives an instruction, ALWAYS evaluate whether it should be memorized. If it contains a convention, preference, correction, workflow, fact, or any persistent knowledge, create a memory immediately. Only skip memorization if the instruction is purely about an ephemeral, one-shot action with no future relevance.",
		"8. **Memorize your own reasoning about the system.** When you read code, trace a call flow, or analyze how a module works, you MUST create a memory of what you learned. This includes: how components interact, why something behaves unexpectedly, what a non-obvious function does, and any pattern or constraint you discover independently — even without the user saying anything.",
		"9. **Never discard an insight.** If you understood something non-trivial while analyzing the system, store it. The next session will start blind — your analysis notes must be externalized into memory to survive.",
	)

	return strings.Join(lines, "\n") + "\n"
}

var memorySkillName = brand.SkillDirName("memory")

func MandateTrigger() string {
	return ide.ModuleMandateTrigger(
		"Memory Management",
		memorySkillName,
		"memory",
		"ALWAYS consult this skill: search memory at session start BEFORE your first response, and again before implementing changes, proposing an approach, or when stuck. This is unconditional — there is no \"only if relevant\" escape. This framework IS your memory; NEVER use IDE/model native memory.\n"+
			"SEARCH ANSWERS WITH TITLES, NOT WITH MEMORIES. A search result is a slug, a title, a type and a score — it carries no memory text, deliberately, so that the tokens go on the one or two memories you actually decide to open rather than on twenty previews. Choosing is yours: read the titles, pick, then call "+brand.MCPToolRef("wiki", "source")+" with `wiki: \"memory\"` on what you picked. Acting on a search result alone is acting on a title you never read. `preview: true` buys a short excerpt per hit when two titles genuinely do not separate — it is the exception.",
		[]string{
			"the session just started and you have not yet searched memory — before the first response, not after it. This is the ONE skill that is due at session start; every other module waits for a trigger of its own to fire",
			"you are about to propose an approach, a design, or a plan",
			"you are stuck, or the second attempt at something is failing the way the first did",
			"the user corrected you, stated a preference, or told you how they want something done",
			"you learned something about this project that the code does not say and the next session would need",
			"two memories you just read disagree, repeat each other, or describe something the code no longer does — fixing that is part of reading them, in the same turn, not a finding to report",
			"the user says they told you this before, or refers to an earlier decision",
			"you are about to write to any IDE-native or model-native memory — do this instead, never that",
			"you are about to open a memory page as a file — you cannot: the store is global and outside your workspace, so " + brand.MCPToolRef("wiki", "source") + " with `wiki: \"memory\"` is the only way to read one",
			"the question is about another project in the ecosystem — its memories hold why it is the way it is; pass its `project_dir` instead of re-deriving that from its code",
			"a memory search came back and you are about to act on it — you cannot: " + brand.MCPToolRef("memory", "search") + " answers with TITLES, so pick the one or two the titles justify and read them with " + brand.MCPToolRef("wiki", "source") + " (`wiki: \"memory\"`) before you conclude anything",
			"a search result is marked `superseded` — it is an OLD revision of the memory named in `current`, so read that one before you state anything about how the system behaves today",
			"the question is how a belief in this project CHANGED — what a memory said before a correction, or why it was revised. Every superseded revision is searchable and the chain is walkable through `previous`; do not answer that from the current memory alone",
		},
		[]string{"memory_search", "memory_insert", "memory_update", "memory_list", "memory_important", "memory_promote", "memory_demote", "memory_delete", "memory_index", "memory_schema", "memory_export", "memory_sync", "memory_remove", "wiki_source"},
	)
}

func InstallRule(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}

	if err := ide.UpsertMandateTrigger(projectDir, ideName, "mem_rule", MandateTrigger()); err != nil {
		return err
	}

	return InstallSkill(projectDir, ideName)
}

func InstallSkill(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	contexts := AllContextDirs()
	skillContent := brand.ResolveModuleSkill("memory", RuleContent(contexts))
	frontmatter, err := ide.SkillFrontmatter(memorySkillName, "Persistent memory across sessions — this framework IS your memory. MANDATORY at conversation start: search memory before responding. Use when: user corrects, teaches, explains, instructs, or guides you; you complete a task, fix a bug, or make a design decision; you discover something unexpected or infer a non-obvious pattern; you are stuck or implementing significant changes (check prior constraints); memory maintenance (gc, consolidation, promote/demote).")
	if err != nil {
		return err
	}
	return ide.InstallManagedSkill(projectDir, ideName, memorySkillName, frontmatter+skillContent)
}

func RemoveRule(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}

	return ide.RemoveMandateTrigger(projectDir, ideName, "mem_rule")
}

func RemoveSkill(projectDir, ideName string) error {
	if projectDir == "" {
		var err error
		projectDir, err = os.Getwd()
		if err != nil {
			return err
		}
	}
	return ide.RemoveManagedSkill(projectDir, ideName, memorySkillName)
}
