package brand

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSimpleBrandFunctions(t *testing.T) {
	// Backup and restore global brand settings if modified (though here they are static)
	origBrand := Brand
	origDisplayName := DisplayName
	origGitHubRepo := GitHubRepo
	origDefaultHubBucket := DefaultHubBucket
	origDefaultHubRegion := DefaultHubRegion
	origSelfUpdateURL := SelfUpdateURL
	defer func() {
		Brand = origBrand
		DisplayName = origDisplayName
		GitHubRepo = origGitHubRepo
		DefaultHubBucket = origDefaultHubBucket
		DefaultHubRegion = origDefaultHubRegion
		SelfUpdateURL = origSelfUpdateURL
	}()

	Brand = "testbrand"
	DisplayName = "Test Display Name"
	GitHubRepo = "test/repo"
	DefaultHubBucket = "test-hub-bucket"
	DefaultHubRegion = "us-east-1"
	SelfUpdateURL = "https://my-server.example.com/releases/latest"

	if DotDir() != ".testbrand" {
		t.Errorf("DotDir() = %q; want %q", DotDir(), ".testbrand")
	}
	if LockFileName() != "testbrand.lock.json" {
		t.Errorf("LockFileName() = %q; want %q", LockFileName(), "testbrand.lock.json")
	}
	if IgnoreMarker() != "TESTBRAND AUTOGENERATED IGNORER" {
		t.Errorf("IgnoreMarker() = %q; want %q", IgnoreMarker(), "TESTBRAND AUTOGENERATED IGNORER")
	}
	if ManagedBlockMarker() != "TESTBRAND MANAGED BLOCK" {
		t.Errorf("ManagedBlockMarker() = %q; want %q", ManagedBlockMarker(), "TESTBRAND MANAGED BLOCK")
	}
	if BinName() != "testbrand" {
		t.Errorf("BinName() = %q; want %q", BinName(), "testbrand")
	}
	if BinNameWindows() != "testbrand.exe" {
		t.Errorf("BinNameWindows() = %q; want %q", BinNameWindows(), "testbrand.exe")
	}
	if EnvPrefix() != "TESTBRAND" {
		t.Errorf("EnvPrefix() = %q; want %q", EnvPrefix(), "TESTBRAND")
	}
	if EnvVar("SUF") != "TESTBRAND_SUF" {
		t.Errorf("EnvVar() = %q; want %q", EnvVar("SUF"), "TESTBRAND_SUF")
	}
	if MCPServerName("mod") != "testbrand-mod-mcp" {
		t.Errorf("MCPServerName() = %q; want %q", MCPServerName("mod"), "testbrand-mod-mcp")
	}
	if TempDirPrefix("mod") != "testbrand-mod-" {
		t.Errorf("TempDirPrefix() = %q; want %q", TempDirPrefix("mod"), "testbrand-mod-")
	}
	if SkillDirName("mod") != "testbrand-mod" {
		t.Errorf("SkillDirName() = %q; want %q", SkillDirName("mod"), "testbrand-mod")
	}
	if defaultRulePlaceholder() != "{{_TESTBRAND_DEFAULT_RULE_CONTENT_}}" {
		t.Errorf("defaultRulePlaceholder() = %q; want %q", defaultRulePlaceholder(), "{{_TESTBRAND_DEFAULT_RULE_CONTENT_}}")
	}
	if defaultSkillPlaceholder() != "{{_TESTBRAND_DEFAULT_SKILL_CONTENT_}}" {
		t.Errorf("defaultSkillPlaceholder() = %q; want %q", defaultSkillPlaceholder(), "{{_TESTBRAND_DEFAULT_SKILL_CONTENT_}}")
	}
}

func TestCapitalize(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"", ""},
		{"a", "A"},
		{"abc", "Abc"},
		{"ABC", "ABC"},
		{"1abc", "1abc"},
	}

	for _, tc := range tests {
		res := Capitalize(tc.input)
		if res != tc.expected {
			t.Errorf("Capitalize(%q) = %q; want %q", tc.input, res, tc.expected)
		}
	}
}

func TestGlobalDirsAndResolvers(t *testing.T) {
	// Save environment
	origHome := os.Getenv("HOME")
	defer func() { _ = os.Setenv("HOME", origHome) }()

	tempDir, err := os.MkdirTemp("", "brand-test-home")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tempDir) }()

	_ = os.Setenv("HOME", tempDir)

	// Restored, unlike every other Brand reassignment in this file, which all defer it.
	// Leaving it set leaks "testbrand2" into every test that runs after this one, and
	// anything deriving a path from Brand then computes it against a brand that does not
	// exist — silently, because the value is still a valid string.
	origBrand := Brand
	defer func() { Brand = origBrand }()
	Brand = "testbrand2"

	expectedGlobalDir := filepath.Join(tempDir, ".testbrand2")
	if GlobalDir() != expectedGlobalDir {
		t.Errorf("GlobalDir() = %q; want %q", GlobalDir(), expectedGlobalDir)
	}

	expectedGlobalRulesDir := filepath.Join(expectedGlobalDir, "rules")
	if GlobalRulesDir() != expectedGlobalRulesDir {
		t.Errorf("GlobalRulesDir() = %q; want %q", GlobalRulesDir(), expectedGlobalRulesDir)
	}

	expectedHubRulesDir := filepath.Join(expectedGlobalDir, "hub", "rules")
	if HubRulesDir() != expectedHubRulesDir {
		t.Errorf("HubRulesDir() = %q; want %q", HubRulesDir(), expectedHubRulesDir)
	}

	res := ResolveModuleRule("mymod", "default-val")
	if res != "default-val" {
		t.Errorf("ResolveModuleRule fallback = %q; want %q", res, "default-val")
	}

	resSkill := ResolveModuleSkill("myskill", "default-skill-val")
	if resSkill != "default-skill-val" {
		t.Errorf("ResolveModuleSkill fallback = %q; want %q", resSkill, "default-skill-val")
	}

	// Now set up local rules dir in current working directory
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get wd: %v", err)
	}

	localRulesDir := filepath.Join(wd, ".testbrand2", "rules")
	err = os.MkdirAll(localRulesDir, 0755)
	if err != nil {
		t.Fatalf("failed to create local rules dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(filepath.Join(wd, ".testbrand2")) }()

	localRuleFile := filepath.Join(localRulesDir, "mymod.md")
	ruleContent := "local-rule-content: {{_TESTBRAND2_DEFAULT_RULE_CONTENT_}}"
	err = os.WriteFile(localRuleFile, []byte(ruleContent), 0644)
	if err != nil {
		t.Fatalf("failed to write local rule: %v", err)
	}

	localSkillFile := filepath.Join(localRulesDir, "myskill_skill.md")
	skillContent := "local-skill-content: {{_TESTBRAND2_DEFAULT_SKILL_CONTENT_}}"
	err = os.WriteFile(localSkillFile, []byte(skillContent), 0644)
	if err != nil {
		t.Fatalf("failed to write local skill: %v", err)
	}

	res = ResolveModuleRule("mymod", "default-val")
	expectedRule := "local-rule-content: default-val"
	if res != expectedRule {
		t.Errorf("ResolveModuleRule local = %q; want %q", res, expectedRule)
	}

	// Test ResolveModuleSkill from local rules dir
	resSkill = ResolveModuleSkill("myskill", "default-skill-val")
	expectedSkill := "local-skill-content: default-skill-val"
	if resSkill != expectedSkill {
		t.Errorf("ResolveModuleSkill local = %q; want %q", resSkill, expectedSkill)
	}

	// Clean up local rules file to test global fallback
	_ = os.RemoveAll(filepath.Join(wd, ".testbrand2"))

	err = os.MkdirAll(expectedGlobalRulesDir, 0755)
	if err != nil {
		t.Fatalf("failed to create global rules dir: %v", err)
	}

	globalRuleFile := filepath.Join(expectedGlobalRulesDir, "mymod.md")
	err = os.WriteFile(globalRuleFile, []byte(ruleContent), 0644)
	if err != nil {
		t.Fatalf("failed to write global rule: %v", err)
	}

	globalSkillFile := filepath.Join(expectedGlobalRulesDir, "myskill_skill.md")
	err = os.WriteFile(globalSkillFile, []byte(skillContent), 0644)
	if err != nil {
		t.Fatalf("failed to write global skill: %v", err)
	}

	res = ResolveModuleRule("mymod", "default-val")
	if res != expectedRule {
		t.Errorf("ResolveModuleRule global = %q; want %q", res, expectedRule)
	}

	// Test ResolveModuleSkill from global rules dir
	resSkill = ResolveModuleSkill("myskill", "default-skill-val")
	if resSkill != expectedSkill {
		t.Errorf("ResolveModuleSkill global = %q; want %q", resSkill, expectedSkill)
	}

	// Clean up global rules to test Hub fallback
	_ = os.RemoveAll(expectedGlobalRulesDir)

	// Set up Hub rules dir (simulates main branch of Hub Git repo)
	err = os.MkdirAll(expectedHubRulesDir, 0755)
	if err != nil {
		t.Fatalf("failed to create hub rules dir: %v", err)
	}

	hubRuleContent := "hub-rule-content: {{_TESTBRAND2_DEFAULT_RULE_CONTENT_}}"
	hubRuleFile := filepath.Join(expectedHubRulesDir, "mymod.md")
	err = os.WriteFile(hubRuleFile, []byte(hubRuleContent), 0644)
	if err != nil {
		t.Fatalf("failed to write hub rule: %v", err)
	}

	hubSkillContent := "hub-skill-content: {{_TESTBRAND2_DEFAULT_SKILL_CONTENT_}}"
	hubSkillFile := filepath.Join(expectedHubRulesDir, "myskill_skill.md")
	err = os.WriteFile(hubSkillFile, []byte(hubSkillContent), 0644)
	if err != nil {
		t.Fatalf("failed to write hub skill: %v", err)
	}

	res = ResolveModuleRule("mymod", "default-val")
	expectedHubRule := "hub-rule-content: default-val"
	if res != expectedHubRule {
		t.Errorf("ResolveModuleRule hub = %q; want %q", res, expectedHubRule)
	}

	// Test ResolveModuleSkill from Hub rules dir
	resSkill = ResolveModuleSkill("myskill", "default-skill-val")
	expectedHubSkill := "hub-skill-content: default-skill-val"
	if resSkill != expectedHubSkill {
		t.Errorf("ResolveModuleSkill hub = %q; want %q", resSkill, expectedHubSkill)
	}

	// Test precedence: global CLI override wins over Hub override
	err = os.MkdirAll(expectedGlobalRulesDir, 0755)
	if err != nil {
		t.Fatalf("failed to re-create global rules dir: %v", err)
	}
	err = os.WriteFile(globalRuleFile, []byte(ruleContent), 0644)
	if err != nil {
		t.Fatalf("failed to re-write global rule: %v", err)
	}
	err = os.WriteFile(globalSkillFile, []byte(skillContent), 0644)
	if err != nil {
		t.Fatalf("failed to re-write global skill: %v", err)
	}

	res = ResolveModuleRule("mymod", "default-val")
	if res != expectedRule {
		t.Errorf("ResolveModuleRule precedence (global > hub) = %q; want %q", res, expectedRule)
	}
	resSkill = ResolveModuleSkill("myskill", "default-skill-val")
	if resSkill != expectedSkill {
		t.Errorf("ResolveModuleSkill precedence (global > hub) = %q; want %q", resSkill, expectedSkill)
	}
}

func TestGlobalDirErr(t *testing.T) {
	// Save environment and clear HOME/USERPROFILE to cause UserHomeDir failure if possible
	origHome := os.Getenv("HOME")
	origUserProfile := os.Getenv("USERPROFILE")
	defer func() {
		_ = os.Setenv("HOME", origHome)
		_ = os.Setenv("USERPROFILE", origUserProfile)
	}()

	_ = os.Unsetenv("HOME")
	_ = os.Unsetenv("USERPROFILE")

	// Verify GlobalDir returns empty string on error
	// Note: on some environments, os.UserHomeDir might still succeed or fail depending on os configuration.
	// But we test the fallback branch safety.
	res := GlobalDir()
	if res == "" {
		// If it did fail, GlobalRulesDir should also return empty
		if GlobalRulesDir() != "" {
			t.Errorf("expected GlobalRulesDir() to be empty when GlobalDir() is empty")
		}
		// HubRulesDir should also return empty when GlobalDir is empty
		if HubRulesDir() != "" {
			t.Errorf("expected HubRulesDir() to be empty when GlobalDir() is empty")
		}
		// RuntimeDir should also return empty when GlobalDir is empty
		if RuntimeDir("v1.0.0") != "" {
			t.Errorf("expected RuntimeDir() to be empty when GlobalDir() is empty")
		}
	}
}

func TestMCPToolNameAndRef(t *testing.T) {
	origBrand := Brand
	defer func() { Brand = origBrand }()

	Brand = "testbrand"

	if got := MCPToolName("ast"); got != "testbrand_ast" {
		t.Errorf("MCPToolName(ast) = %q; want %q", got, "testbrand_ast")
	}

	if got := MCPToolName("improvements", "backlog_add"); got != "testbrand_improvements_backlog_add" {
		t.Errorf("MCPToolName(improvements, backlog_add) = %q; want %q", got, "testbrand_improvements_backlog_add")
	}

	if got := MCPToolRef("ast"); got != "`testbrand_ast`" {
		t.Errorf("MCPToolRef(ast) = %q; want %q", got, "`testbrand_ast`")
	}

	if got := MCPToolRef("improvements", "backlog_add"); got != "`testbrand_improvements_backlog_add`" {
		t.Errorf("MCPToolRef(improvements, backlog_add) = %q; want %q", got, "`testbrand_improvements_backlog_add`")
	}
}

func TestRuntimeDir(t *testing.T) {
	origHome := os.Getenv("HOME")
	defer func() { _ = os.Setenv("HOME", origHome) }()

	origBrand := Brand
	defer func() { Brand = origBrand }()

	tempDir, err := os.MkdirTemp("", "brand-runtime-test")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tempDir) }()

	_ = os.Setenv("HOME", tempDir)
	Brand = "testbrand3"

	expected := filepath.Join(tempDir, ".testbrand3", "runtime", "v1.2.3")
	if got := RuntimeDir("v1.2.3"); got != expected {
		t.Errorf("RuntimeDir(v1.2.3) = %q; want %q", got, expected)
	}
}

func TestCoreSkillIDs(t *testing.T) {
	origBrand := Brand
	defer func() { Brand = origBrand }()
	Brand = "testbrand"

	ids := CoreSkillIDs()
	expectedIDs := []string{
		"testbrand-ast",
		"testbrand-hub",
		"testbrand-knowledge",
		"testbrand-memory",
	}
	for _, id := range expectedIDs {
		if !ids[id] {
			t.Errorf("CoreSkillIDs() missing %q", id)
		}
	}
	if len(ids) != len(expectedIDs) {
		t.Errorf("CoreSkillIDs() has %d entries; want %d", len(ids), len(expectedIDs))
	}
}
