package brand

import (
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

var Brand = "graphit"

var GitHubRepo = ""

var DisplayName = "Graphit Code: A Powerful Agent Harness for Enterprise Software Ecosystems"

var DefaultHubRepoURL = ""

var DefaultMemoryRepoURL = ""

var SelfUpdateURL = ""

func DotDir() string { return "." + Brand }

func LockFileName() string { return Brand + ".lock.json" }

func IgnoreMarker() string { return strings.ToUpper(Brand) + " AUTOGENERATED IGNORER" }

func ManagedBlockMarker() string { return strings.ToUpper(Brand) + " MANAGED BLOCK" }

func BinName() string { return Brand }

func BinNameWindows() string { return Brand + ".exe" }

func EnvPrefix() string { return strings.ToUpper(Brand) }

func EnvVar(suffix string) string { return EnvPrefix() + "_" + suffix }

func MCPServerName(module string) string { return Brand + "-" + module + "-mcp" }

func MCPToolName(parts ...string) string { return Brand + "_" + strings.Join(parts, "_") }

func MCPToolRef(parts ...string) string { return "`" + MCPToolName(parts...) + "`" }

func TempDirPrefix(module string) string { return Brand + "-" + module + "-" }

func ManagedMCPKey() string { return "_" + Brand + "ManagedMcpKeys" }

func GlobalDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, "."+Brand)
}

// RuntimeDir returns a version-scoped directory for framework-managed runtime
// files: ~/.graphit/runtime/<version>/. These files are managed by the binary
// and may be overwritten on each version upgrade. User customizations should
// go in GlobalDir() instead.
func RuntimeDir(version string) string {
	d := GlobalDir()
	if d == "" {
		return ""
	}
	return filepath.Join(d, "runtime", version)
}

func GlobalRulesDir() string {
	d := GlobalDir()
	if d == "" {
		return ""
	}
	return filepath.Join(d, "rules")
}

func HubRulesDir() string {
	d := GlobalDir()
	if d == "" {
		return ""
	}
	return filepath.Join(d, "hub", "rules")
}

func defaultRulePlaceholder() string {
	return "{{_" + strings.ToUpper(Brand) + "_DEFAULT_RULE_CONTENT_}}"
}

func ResolveModuleRule(module, defaultContent string) string {
	placeholder := defaultRulePlaceholder()

	if wd, err := os.Getwd(); err == nil {
		projectPath := filepath.Join(wd, DotDir(), "rules", module+".md")
		if data, err := os.ReadFile(projectPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	rulesDir := GlobalRulesDir()
	if rulesDir != "" {
		globalPath := filepath.Join(rulesDir, module+".md")
		if data, err := os.ReadFile(globalPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	hubDir := HubRulesDir()
	if hubDir != "" {
		hubPath := filepath.Join(hubDir, module+".md")
		if data, err := os.ReadFile(hubPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	return defaultContent
}

func SkillDirName(module string) string {
	return Brand + "-" + module
}

func CoreSkillIDs() map[string]bool {
	return map[string]bool{
		SkillDirName("ast"):          true,
		SkillDirName("hub"):          true,
		SkillDirName("knowledge"):    true,
		SkillDirName("memory"):       true,
		SkillDirName("improvements"): true,
	}
}

func defaultSkillPlaceholder() string {
	return "{{_" + strings.ToUpper(Brand) + "_DEFAULT_SKILL_CONTENT_}}"
}

func ResolveModuleSkill(module, defaultContent string) string {
	placeholder := defaultSkillPlaceholder()
	fileName := module + "_skill.md"

	if wd, err := os.Getwd(); err == nil {
		projectPath := filepath.Join(wd, DotDir(), "rules", fileName)
		if data, err := os.ReadFile(projectPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	rulesDir := GlobalRulesDir()
	if rulesDir != "" {
		globalPath := filepath.Join(rulesDir, fileName)
		if data, err := os.ReadFile(globalPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	hubDir := HubRulesDir()
	if hubDir != "" {
		hubPath := filepath.Join(hubDir, fileName)
		if data, err := os.ReadFile(hubPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	return defaultContent
}

func Capitalize(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

// UniversalAIOptimizedNote returns a short reminder to always set ai_optimized: true.
// Used in skill content bodies so agents see it regardless of which skill they read.
func UniversalAIOptimizedNote() string {
	return "> **\U0001f512 UNIVERSAL RULE:** Always set `ai_optimized: true` on EVERY " +
		Capitalize(Brand) + " MCP tool call. No exceptions.\n"
}
