package brand

import (
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

var Brand = "graphit"

var GitHubRepo = ""

var DisplayName = "Graphit Code: A Powerful Agent Harness for Enterprise Software Ecosystems"

var DefaultHubBucket = ""

var DefaultHubRegion = ""

var DefaultHubEndpoint = ""

var SelfUpdateURL = ""

func DotDir() string { return "." + Brand }

// RuntimeSubdir holds generated project-local state: caches, locks, stamps, hashes,
// exports, dream output and the per-project daemon log.
func RuntimeSubdir() string { return "runtime" }

// ProjectRuntimePath returns <projectDir>/.brand/runtime/<parts...>.
//
// Every writer of project-local generated state goes through here. Project-local
// grammar binaries are the other ignored tree and use their grammar resolvers.
func ProjectRuntimePath(projectDir string, parts ...string) string {
	return filepath.Join(append([]string{projectDir, DotDir(), RuntimeSubdir()}, parts...)...)
}

// GitignoreContent is the block `graphit init` writes into the project's
// .gitignore. It ignores generated runtime state and project-local grammar
// binaries while leaving rule and query overrides visible.
//
// NOTE: the leading "**/" is what keeps it matching at any depth. A pattern with a
// separator in the middle is anchored to the directory of the .gitignore that
// declares it, so a bare ".brand/runtime/" would ignore the project's own machine
// state and expose that of every nested project, test fixture and sub-checkout
// below it.
func GitignoreContent() string {
	prefix := "**/" + DotDir() + "/"
	return prefix + RuntimeSubdir() + "/\n" + prefix + "grammars/"
}

func LockFileName() string { return Brand + ".lock.json" }

func IgnoreMarker() string { return strings.ToUpper(Brand) + " AUTOGENERATED IGNORER" }

func ManagedBlockMarker() string { return strings.ToUpper(Brand) + " MANAGED BLOCK" }

func BinName() string { return Brand }

func BinNameWindows() string { return Brand + ".exe" }

func EnvPrefix() string { return strings.ToUpper(Brand) }

func EnvVar(suffix string) string { return EnvPrefix() + "_" + suffix }

func MCPServerName(module string) string { return Brand + "-" + module + "-mcp" }

func MCPToolName(parts ...string) string { return Brand + "_" + strings.Join(parts, "_") }

func MCPToolRef(parts ...string) string { return "`" + MCPToolName(parts...) + "`" }

func TempDirPrefix(module string) string { return Brand + "-" + module + "-" }

var processStartDir, _ = os.Getwd()

// GlobalDir resolves the global brand directory.
// The <BRAND>_GLOBAL_DIR override is documented in docs/architecture/storage_layout.md.
func GlobalDir() string {
	if override := strings.TrimSpace(os.Getenv(EnvVar("GLOBAL_DIR"))); override != "" {
		if filepath.IsAbs(override) {
			return filepath.Clean(override)
		}
		return filepath.Join(processStartDir, override)
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, "."+Brand)
}

// RuntimeDir returns a version-scoped directory for framework-managed runtime
// files: ~/.graphit/runtime/<version>/. These files are managed by the binary
// and may be overwritten on each version upgrade. User customizations should
// go in GlobalDir() instead.
func RuntimeDir(version string) string {
	d := GlobalDir()
	if d == "" {
		return ""
	}
	return filepath.Join(d, "runtime", version)
}

func GlobalRulesDir() string {
	d := GlobalDir()
	if d == "" {
		return ""
	}
	return filepath.Join(d, "rules")
}

func HubRulesDir() string {
	d := GlobalDir()
	if d == "" {
		return ""
	}
	return filepath.Join(d, "hub", "rules")
}

func defaultRulePlaceholder() string {
	return "{{_" + strings.ToUpper(Brand) + "_DEFAULT_RULE_CONTENT_}}"
}

func ResolveModuleRule(module, defaultContent string) string {
	wd, _ := os.Getwd()
	return ResolveModuleRuleIn(wd, module, defaultContent)
}

// ResolveModuleRuleIn resolves a module mandate for an explicit project. Hook
// commands use this instead of process cwd because they may run from a nested
// directory or a host-controlled working directory.
func ResolveModuleRuleIn(projectDir, module, defaultContent string) string {
	placeholder := defaultRulePlaceholder()

	if projectDir != "" {
		projectPath := filepath.Join(projectDir, DotDir(), "rules", module+".md")
		if data, err := os.ReadFile(projectPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	rulesDir := GlobalRulesDir()
	if rulesDir != "" {
		globalPath := filepath.Join(rulesDir, module+".md")
		if data, err := os.ReadFile(globalPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	hubDir := HubRulesDir()
	if hubDir != "" {
		hubPath := filepath.Join(hubDir, module+".md")
		if data, err := os.ReadFile(hubPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	return defaultContent
}

func SkillDirName(module string) string {
	return Brand + "-" + module
}

func CoreSkillIDs() map[string]bool {
	return map[string]bool{
		SkillDirName("ast"):       true,
		SkillDirName("hub"):       true,
		SkillDirName("knowledge"): true,
		SkillDirName("memory"):    true,
	}
}

func defaultSkillPlaceholder() string {
	return "{{_" + strings.ToUpper(Brand) + "_DEFAULT_SKILL_CONTENT_}}"
}

func ResolveModuleSkill(module, defaultContent string) string {
	wd, _ := os.Getwd()
	return ResolveModuleSkillIn(wd, module, defaultContent)
}

func ResolveModuleSkillIn(projectDir, module, defaultContent string) string {
	placeholder := defaultSkillPlaceholder()
	fileName := module + "_skill.md"

	if projectDir != "" {
		projectPath := filepath.Join(projectDir, DotDir(), "rules", fileName)
		if data, err := os.ReadFile(projectPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	rulesDir := GlobalRulesDir()
	if rulesDir != "" {
		globalPath := filepath.Join(rulesDir, fileName)
		if data, err := os.ReadFile(globalPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	hubDir := HubRulesDir()
	if hubDir != "" {
		hubPath := filepath.Join(hubDir, fileName)
		if data, err := os.ReadFile(hubPath); err == nil {
			return strings.ReplaceAll(string(data), placeholder, defaultContent)
		}
	}

	return defaultContent
}

func Capitalize(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}
