package brand

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSimpleBrandFunctions(t *testing.T) {
	// Backup and restore global brand settings if modified (though here they are static)
	origBrand := Brand
	origDisplayName := DisplayName
	origGitHubRepo := GitHubRepo
	origDefaultHubRepoURL := DefaultHubRepoURL
	origDefaultMemoryRepoURL := DefaultMemoryRepoURL
	defer func() {
		Brand = origBrand
		DisplayName = origDisplayName
		GitHubRepo = origGitHubRepo
		DefaultHubRepoURL = origDefaultHubRepoURL
		DefaultMemoryRepoURL = origDefaultMemoryRepoURL
	}()

	Brand = "testbrand"
	DisplayName = "Test Display Name"
	GitHubRepo = "test/repo"
	DefaultHubRepoURL = "git@github.com:test/repo.git"
	DefaultMemoryRepoURL = "git@github.com:test/memory.git"

	if DotDir() != ".testbrand" {
		t.Errorf("DotDir() = %q; want %q", DotDir(), ".testbrand")
	}
	if LockFileName() != "testbrand.lock.json" {
		t.Errorf("LockFileName() = %q; want %q", LockFileName(), "testbrand.lock.json")
	}
	if HookMarker() != "# testbrand-managed-hook" {
		t.Errorf("HookMarker() = %q; want %q", HookMarker(), "# testbrand-managed-hook")
	}
	if IgnoreMarker() != "TESTBRAND AUTOGENERATED IGNORER" {
		t.Errorf("IgnoreMarker() = %q; want %q", IgnoreMarker(), "TESTBRAND AUTOGENERATED IGNORER")
	}
	if ManagedBlockMarker() != "TESTBRAND MANAGED BLOCK" {
		t.Errorf("ManagedBlockMarker() = %q; want %q", ManagedBlockMarker(), "TESTBRAND MANAGED BLOCK")
	}
	if BinName() != "testbrand" {
		t.Errorf("BinName() = %q; want %q", BinName(), "testbrand")
	}
	if BinNameWindows() != "testbrand.exe" {
		t.Errorf("BinNameWindows() = %q; want %q", BinNameWindows(), "testbrand.exe")
	}
	if EnvPrefix() != "TESTBRAND" {
		t.Errorf("EnvPrefix() = %q; want %q", EnvPrefix(), "TESTBRAND")
	}
	if EnvVar("SUF") != "TESTBRAND_SUF" {
		t.Errorf("EnvVar() = %q; want %q", EnvVar("SUF"), "TESTBRAND_SUF")
	}
	if MCPServerName("mod") != "testbrand-mod-mcp" {
		t.Errorf("MCPServerName() = %q; want %q", MCPServerName("mod"), "testbrand-mod-mcp")
	}
	if PrinterPrefix("mod") != "testbrand:mod" {
		t.Errorf("PrinterPrefix() = %q; want %q", PrinterPrefix("mod"), "testbrand:mod")
	}
	if TempDirPrefix("mod") != "testbrand-mod-" {
		t.Errorf("TempDirPrefix() = %q; want %q", TempDirPrefix("mod"), "testbrand-mod-")
	}
	if ManagedMCPKey() != "_testbrandManagedMcpKeys" {
		t.Errorf("ManagedMCPKey() = %q; want %q", ManagedMCPKey(), "_testbrandManagedMcpKeys")
	}
	if SkillDirName("mod") != "testbrand-mod" {
		t.Errorf("SkillDirName() = %q; want %q", SkillDirName("mod"), "testbrand-mod")
	}
	if ManagedSkillPrefix() != "testbrand-" {
		t.Errorf("ManagedSkillPrefix() = %q; want %q", ManagedSkillPrefix(), "testbrand-")
	}
	if defaultRulePlaceholder() != "{{_TESTBRAND_DEFAULT_RULE_CONTENT_}}" {
		t.Errorf("defaultRulePlaceholder() = %q; want %q", defaultRulePlaceholder(), "{{_TESTBRAND_DEFAULT_RULE_CONTENT_}}")
	}
	if defaultSkillPlaceholder() != "{{_TESTBRAND_DEFAULT_SKILL_CONTENT_}}" {
		t.Errorf("defaultSkillPlaceholder() = %q; want %q", defaultSkillPlaceholder(), "{{_TESTBRAND_DEFAULT_SKILL_CONTENT_}}")
	}
}

func TestCapitalize(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"", ""},
		{"a", "A"},
		{"abc", "Abc"},
		{"ABC", "ABC"},
		{"1abc", "1abc"},
	}

	for _, tc := range tests {
		res := Capitalize(tc.input)
		if res != tc.expected {
			t.Errorf("Capitalize(%q) = %q; want %q", tc.input, res, tc.expected)
		}
	}
}

func TestGlobalDirsAndResolvers(t *testing.T) {
	// Save environment
	origHome := os.Getenv("HOME")
	defer func() { _ = os.Setenv("HOME", origHome) }()

	// Create temp directory for testing
	tempDir, err := os.MkdirTemp("", "brand-test-home")
	if err != nil {
		t.Fatalf("failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tempDir) }()

	// Set HOME to tempDir
	_ = os.Setenv("HOME", tempDir)

	Brand = "testbrand2"

	expectedGlobalDir := filepath.Join(tempDir, ".testbrand2")
	if GlobalDir() != expectedGlobalDir {
		t.Errorf("GlobalDir() = %q; want %q", GlobalDir(), expectedGlobalDir)
	}

	expectedGlobalRulesDir := filepath.Join(expectedGlobalDir, "rules")
	if GlobalRulesDir() != expectedGlobalRulesDir {
		t.Errorf("GlobalRulesDir() = %q; want %q", GlobalRulesDir(), expectedGlobalRulesDir)
	}

	// Test ResolveModuleRule and ResolveModuleSkill: fallback to defaultContent
	res := ResolveModuleRule("mymod", "default-val")
	if res != "default-val" {
		t.Errorf("ResolveModuleRule fallback = %q; want %q", res, "default-val")
	}

	resSkill := ResolveModuleSkill("myskill", "default-skill-val")
	if resSkill != "default-skill-val" {
		t.Errorf("ResolveModuleSkill fallback = %q; want %q", resSkill, "default-skill-val")
	}

	// Now set up local rules dir in current working directory
	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get wd: %v", err)
	}

	localRulesDir := filepath.Join(wd, ".testbrand2", "rules")
	err = os.MkdirAll(localRulesDir, 0755)
	if err != nil {
		t.Fatalf("failed to create local rules dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(filepath.Join(wd, ".testbrand2")) }()

	// Create local rule file
	localRuleFile := filepath.Join(localRulesDir, "mymod.md")
	ruleContent := "local-rule-content: {{_TESTBRAND2_DEFAULT_RULE_CONTENT_}}"
	err = os.WriteFile(localRuleFile, []byte(ruleContent), 0644)
	if err != nil {
		t.Fatalf("failed to write local rule: %v", err)
	}

	// Create local skill file
	localSkillFile := filepath.Join(localRulesDir, "myskill_skill.md")
	skillContent := "local-skill-content: {{_TESTBRAND2_DEFAULT_SKILL_CONTENT_}}"
	err = os.WriteFile(localSkillFile, []byte(skillContent), 0644)
	if err != nil {
		t.Fatalf("failed to write local skill: %v", err)
	}

	// Test ResolveModuleRule from local rules dir
	res = ResolveModuleRule("mymod", "default-val")
	expectedRule := "local-rule-content: default-val"
	if res != expectedRule {
		t.Errorf("ResolveModuleRule local = %q; want %q", res, expectedRule)
	}

	// Test ResolveModuleSkill from local rules dir
	resSkill = ResolveModuleSkill("myskill", "default-skill-val")
	expectedSkill := "local-skill-content: default-skill-val"
	if resSkill != expectedSkill {
		t.Errorf("ResolveModuleSkill local = %q; want %q", resSkill, expectedSkill)
	}

	// Clean up local rules file to test global fallback
	_ = os.RemoveAll(filepath.Join(wd, ".testbrand2"))

	// Set up global rules dir
	err = os.MkdirAll(expectedGlobalRulesDir, 0755)
	if err != nil {
		t.Fatalf("failed to create global rules dir: %v", err)
	}

	// Create global rule file
	globalRuleFile := filepath.Join(expectedGlobalRulesDir, "mymod.md")
	err = os.WriteFile(globalRuleFile, []byte(ruleContent), 0644)
	if err != nil {
		t.Fatalf("failed to write global rule: %v", err)
	}

	// Create global skill file
	globalSkillFile := filepath.Join(expectedGlobalRulesDir, "myskill_skill.md")
	err = os.WriteFile(globalSkillFile, []byte(skillContent), 0644)
	if err != nil {
		t.Fatalf("failed to write global skill: %v", err)
	}

	// Test ResolveModuleRule from global rules dir
	res = ResolveModuleRule("mymod", "default-val")
	if res != expectedRule {
		t.Errorf("ResolveModuleRule global = %q; want %q", res, expectedRule)
	}

	// Test ResolveModuleSkill from global rules dir
	resSkill = ResolveModuleSkill("myskill", "default-skill-val")
	if resSkill != expectedSkill {
		t.Errorf("ResolveModuleSkill global = %q; want %q", resSkill, expectedSkill)
	}
}

func TestGlobalDirErr(t *testing.T) {
	// Save environment and clear HOME/USERPROFILE to cause UserHomeDir failure if possible
	origHome := os.Getenv("HOME")
	origUserProfile := os.Getenv("USERPROFILE")
	defer func() {
		_ = os.Setenv("HOME", origHome)
		_ = os.Setenv("USERPROFILE", origUserProfile)
	}()

	_ = os.Unsetenv("HOME")
	_ = os.Unsetenv("USERPROFILE")

	// Verify GlobalDir returns empty string on error
	// Note: on some environments, os.UserHomeDir might still succeed or fail depending on os configuration.
	// But we test the fallback branch safety.
	res := GlobalDir()
	if res == "" {
		// If it did fail, GlobalRulesDir should also return empty
		if GlobalRulesDir() != "" {
			t.Errorf("expected GlobalRulesDir() to be empty when GlobalDir() is empty")
		}
	}
}
