name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of graphit-code are you using?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs here. You may want to wrap these in a `<details>` block if they are long.
      render: shell
    validations:
      required: false
