package ast

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/graphit-labs/graphit-code/internal/brand"
)

type ObsidianExporter struct {
	db       GraphDB
	repoPath string
}

func NewObsidianExporter(db GraphDB, repoPath string) *ObsidianExporter {
	return &ObsidianExporter{db: db, repoPath: repoPath}
}

func (e *ObsidianExporter) Export(ctx context.Context, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	if err := e.writeIndex(ctx, outputDir); err != nil {
		return err
	}
	if err := e.writeFiles(ctx, outputDir); err != nil {
		return err
	}
	if err := e.writeFunctions(ctx, outputDir); err != nil {
		return err
	}
	if err := e.writeClasses(ctx, outputDir); err != nil {
		return err
	}
	if err := e.writeModules(ctx, outputDir); err != nil {
		return err
	}
	if err := e.copyConfig(outputDir); err != nil {
		return err
	}
	return nil
}

func (e *ObsidianExporter) writeIndex(ctx context.Context, dir string) error {

	statsQ := `MATCH (f:File) RETURN count(f) as files`
	fRes, _ := e.db.Query(ctx, statsQ, nil)
	files := 0
	if len(fRes.Records) > 0 {
		if v, ok := fRes.Records[0]["files"]; ok {
			files = toInt(v)
		}
	}

	fnQ := `MATCH (f:Function) RETURN count(f) as fns`
	fnRes, _ := e.db.Query(ctx, fnQ, nil)
	fns := 0
	if len(fnRes.Records) > 0 {
		if v, ok := fnRes.Records[0]["fns"]; ok {
			fns = toInt(v)
		}
	}

	clQ := `MATCH (c:Class) RETURN count(c) as cls`
	clRes, _ := e.db.Query(ctx, clQ, nil)
	cls := 0
	if len(clRes.Records) > 0 {
		if v, ok := clRes.Records[0]["cls"]; ok {
			cls = toInt(v)
		}
	}

	content := fmt.Sprintf(`---
title: %s Knowledge Base
generated: %s
repo: %s
---

# 🧠 %s Knowledge Base

> Auto-generated by %s

## Statistics

| Metric | Count |
|--------|-------|
| Files  | %d |
| Functions | %d |
| Classes | %d |

## Navigation

- [[_files|📁 Files]]
- [[_functions|⚙️ Functions]]
- [[_classes|🧩 Classes]]
- [[_modules|📦 Modules]]
`, brand.DisplayName, time.Now().Format(time.RFC3339), e.repoPath, brand.DisplayName, brand.DisplayName, files, fns, cls)

	return os.WriteFile(filepath.Join(dir, "index.md"), []byte(content), 0o644)
}

var fileTmpl = template.Must(template.New("file").Parse("---\n" +
	"type: file\n" +
	"path: \"{{.Path}}\"\n" +
	"lang: {{.Lang}}\n" +
	"is_dependency: {{.IsDepend}}\n" +
	"---\n\n" +
	"# 📄 {{.Name}}\n\n" +
	"**Path:** `{{.RelPath}}`\n\n" +
	"## Functions\n" +
	"{{range .Functions}}\n" +
	"- [[{{.Name}}|⚙️ {{.Name}}]] (line {{.Line}})\n" +
	"{{- end}}\n\n" +
	"## Classes\n" +
	"{{range .Classes}}\n" +
	"- [[{{.Name}}|🧩 {{.Name}}]] (line {{.Line}})\n" +
	"{{- end}}\n\n" +
	"## Imports\n" +
	"{{range .Imports}}\n" +
	"- [[{{.Name}}|📦 {{.Name}}]]\n" +
	"{{- end}}\n",
))

type fileNote struct {
	Name      string
	Path      string
	RelPath   string
	Lang      string
	IsDepend  bool
	Functions []struct {
		Name string
		Line int
	}
	Classes []struct {
		Name string
		Line int
	}
	Imports []struct{ Name string }
}

func (e *ObsidianExporter) writeFiles(ctx context.Context, dir string) error {
	filesDir := filepath.Join(dir, "files")
	_ = os.MkdirAll(filesDir, 0o755)

	cypher := `
		MATCH (f:File)
		OPTIONAL MATCH (f)-[:CONTAINS]->(fn:Function)
		OPTIONAL MATCH (f)-[:CONTAINS]->(c:Class)
		OPTIONAL MATCH (f)-[:IMPORTS]->(m:Module)
		RETURN f.path as path, f.name as name, f.relative_path as rel_path, f.is_dependency as is_dep,
		       collect(DISTINCT {name: fn.name, line: fn.line_number}) as fns,
		       collect(DISTINCT {name: c.name, line: c.line_number}) as cls,
		       collect(DISTINCT {name: m.name}) as imports
		LIMIT 5000`

	res, err := e.db.Query(ctx, cypher, nil)
	if err != nil {
		return err
	}

	var indexLines []string
	indexLines = append(indexLines, "# 📁 Files\n")

	for _, r := range res.Records {
		name, _ := r["name"].(string)
		if name == "" {
			continue
		}
		path, _ := r["path"].(string)
		relPath, _ := r["rel_path"].(string)
		isDepend, _ := r["is_dep"].(bool)

		note := fileNote{
			Name:     name,
			Path:     path,
			RelPath:  relPath,
			IsDepend: isDepend,
		}

		ext := strings.ToLower(filepath.Ext(name))
		if lang := TreeSitterLangForExtension(ext); lang != "" {
			note.Lang = lang
		}

		if fns, ok := r["fns"].([]any); ok {
			for _, f := range fns {
				if fm, ok := f.(map[string]any); ok {
					fn := struct {
						Name string
						Line int
					}{}
					fn.Name, _ = fm["name"].(string)
					fn.Line = toInt(fm["line"])
					if fn.Name != "" {
						note.Functions = append(note.Functions, fn)
					}
				}
			}
		}

		if cls, ok := r["cls"].([]any); ok {
			for _, c := range cls {
				if cm, ok := c.(map[string]any); ok {
					cl := struct {
						Name string
						Line int
					}{}
					cl.Name, _ = cm["name"].(string)
					cl.Line = toInt(cm["line"])
					if cl.Name != "" {
						note.Classes = append(note.Classes, cl)
					}
				}
			}
		}

		if imports, ok := r["imports"].([]any); ok {
			for _, imp := range imports {
				if im, ok := imp.(map[string]any); ok {
					n, _ := im["name"].(string)
					if n != "" {
						note.Imports = append(note.Imports, struct{ Name string }{n})
					}
				}
			}
		}

		slug := slugify(name)
		notePath := filepath.Join(filesDir, slug+".md")
		f, err := os.Create(notePath)
		if err == nil {
			_ = fileTmpl.Execute(f, note)
			f.Close()
		}
		indexLines = append(indexLines, fmt.Sprintf("- [[files/%s|%s]]", slug, name))
	}

	indexContent := strings.Join(indexLines, "\n")
	return os.WriteFile(filepath.Join(dir, "_files.md"), []byte(indexContent), 0o644)
}

func (e *ObsidianExporter) writeFunctions(ctx context.Context, dir string) error {
	fnsDir := filepath.Join(dir, "functions")
	_ = os.MkdirAll(fnsDir, 0o755)

	cypher := `
		MATCH (fn:Function)
		WHERE fn.is_dependency = false
		OPTIONAL MATCH (f:File)-[:CONTAINS]->(fn)
		RETURN fn.name as name, fn.path as path, fn.line_number as line,
		       fn.docstring as doc, fn.lang as lang, fn.args as args,
		       f.name as file_name
		ORDER BY fn.name
		LIMIT 10000`

	res, err := e.db.Query(ctx, cypher, nil)
	if err != nil {
		return err
	}

	var indexLines []string
	indexLines = append(indexLines, "# ⚙️ Functions\n")

	for _, r := range res.Records {
		name, _ := r["name"].(string)
		if name == "" {
			continue
		}
		path, _ := r["path"].(string)
		doc, _ := r["doc"].(string)
		lang, _ := r["lang"].(string)
		fileName, _ := r["file_name"].(string)
		line := toInt(r["line"])

		slug := slugify(name + "_" + fileName)
		content := fmt.Sprintf(`---
type: function
name: "%s"
file: "%s"
line: %d
lang: %s
---

# ⚙️ %s

**File:** [[files/%s|%s]] — line %d

%s
`,
			name, path, line, lang,
			name,
			slugify(fileName), fileName, line,
			markdownQuote(doc),
		)

		notePath := filepath.Join(fnsDir, slug+".md")
		_ = os.WriteFile(notePath, []byte(content), 0o644)
		indexLines = append(indexLines, fmt.Sprintf("- [[functions/%s|%s]]  `%s`", slug, name, lang))
	}

	return os.WriteFile(filepath.Join(dir, "_functions.md"), []byte(strings.Join(indexLines, "\n")), 0o644)
}

func (e *ObsidianExporter) writeClasses(ctx context.Context, dir string) error {
	clsDir := filepath.Join(dir, "classes")
	_ = os.MkdirAll(clsDir, 0o755)

	cypher := `
		MATCH (c:Class)
		WHERE c.is_dependency = false
		OPTIONAL MATCH (f:File)-[:CONTAINS]->(c)
		OPTIONAL MATCH (c)-[:INHERITS]->(parent:Class)
		RETURN c.name as name, c.path as path, c.line_number as line,
		       c.docstring as doc, c.lang as lang,
		       f.name as file_name,
		       collect(DISTINCT parent.name) as parents
		ORDER BY c.name
		LIMIT 5000`

	res, err := e.db.Query(ctx, cypher, nil)
	if err != nil {
		return err
	}

	var indexLines []string
	indexLines = append(indexLines, "# 🧩 Classes\n")

	for _, r := range res.Records {
		name, _ := r["name"].(string)
		if name == "" {
			continue
		}
		path, _ := r["path"].(string)
		doc, _ := r["doc"].(string)
		lang, _ := r["lang"].(string)
		fileName, _ := r["file_name"].(string)
		line := toInt(r["line"])

		parentsStr := ""
		if parents, ok := r["parents"].([]any); ok {
			pNames := make([]string, 0, len(parents))
			for _, p := range parents {
				if pn, ok := p.(string); ok && pn != "" {
					pNames = append(pNames, fmt.Sprintf("[[classes/%s|%s]]", slugify(pn), pn))
				}
			}
			if len(pNames) > 0 {
				parentsStr = "**Inherits:** " + strings.Join(pNames, ", ") + "\n\n"
			}
		}

		slug := slugify(name + "_" + fileName)
		content := fmt.Sprintf(`---
type: class
name: "%s"
file: "%s"
line: %d
lang: %s
---

# 🧩 %s

**File:** [[files/%s|%s]] — line %d

%s%s
`,
			name, path, line, lang,
			name,
			slugify(fileName), fileName, line,
			parentsStr,
			markdownQuote(doc),
		)

		notePath := filepath.Join(clsDir, slug+".md")
		_ = os.WriteFile(notePath, []byte(content), 0o644)
		indexLines = append(indexLines, fmt.Sprintf("- [[classes/%s|%s]]  `%s`", slug, name, lang))
	}

	return os.WriteFile(filepath.Join(dir, "_classes.md"), []byte(strings.Join(indexLines, "\n")), 0o644)
}

func (e *ObsidianExporter) writeModules(ctx context.Context, dir string) error {
	cypher := `
		MATCH (m:Module)
		RETURN m.name as name, m.lang as lang, m.full_import_name as full
		ORDER BY m.name
		LIMIT 5000`

	res, err := e.db.Query(ctx, cypher, nil)
	if err != nil {
		return err
	}

	var lines []string
	lines = append(lines, "# 📦 Modules\n")
	for _, r := range res.Records {
		name, _ := r["name"].(string)
		lang, _ := r["lang"].(string)
		if name == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("- `%s`  `%s`", name, lang))
	}

	return os.WriteFile(filepath.Join(dir, "_modules.md"), []byte(strings.Join(lines, "\n")), 0o644)
}

func (e *ObsidianExporter) copyConfig(dir string) error {
	obsDir := filepath.Join(dir, ".obsidian")
	_ = os.MkdirAll(obsDir, 0o755)

	appJSON := `{"legacyEditor":false,"livePreview":true}`
	return os.WriteFile(filepath.Join(obsDir, "app.json"), []byte(appJSON), 0o644)
}

func slugify(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}

	result := b.String()
	for strings.Contains(result, "__") {
		result = strings.ReplaceAll(result, "__", "_")
	}
	return strings.Trim(result, "_")
}

func markdownQuote(s string) string {
	if s == "" {
		return ""
	}
	return "> " + strings.ReplaceAll(strings.TrimSpace(s), "\n", "\n> ") + "\n"
}

func toInt(v any) int {
	switch vv := v.(type) {
	case int:
		return vv
	case int32:
		return int(vv)
	case int64:
		return int(vv)
	case float32:
		return int(vv)
	case float64:
		return int(vv)
	}
	return 0
}
