package dream

import (
	"fmt"
	"strings"
	"time"

	"github.com/graphit-labs/graphit-code/internal/brand"
	"github.com/graphit-labs/graphit-code/internal/improvements"
)

func buildDreamPrompt(projectDir, ulid, ide string, subject *Subject) string {
	context := buildDreamContext(projectDir, ulid, ide, subject)
	analysisRules := brand.ResolveModuleRule("dream", buildDefaultAnalysisRules())
	envelope := buildDreamEnvelope(ulid, subject)

	var b strings.Builder
	b.WriteString(context)
	b.WriteString(analysisRules)
	b.WriteString(envelope)
	return b.String()
}

func buildDreamContext(projectDir, ulid, ide string, subject *Subject) string {
	var b strings.Builder

	b.WriteString("# Dream Session — Autonomous Reflection & Improvement\n\n")

	b.WriteString(fmt.Sprintf("**Dream ID**: `%s`\n", ulid))
	b.WriteString(fmt.Sprintf("**Project**: `%s`\n", projectDir))
	b.WriteString(fmt.Sprintf("**Started**: `%s`\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString(fmt.Sprintf("**IDE**: `%s`\n", ide))
	b.WriteString(fmt.Sprintf("**Tool**: `%s`\n\n", brand.BinName()))

	b.WriteString("## Context\n\n")
	b.WriteString("You are an autonomous AI agent running locally during an idle ")
	b.WriteString("period of this project. Your task is to deeply reflect on the codebase, ")
	b.WriteString("analyze the developer's work patterns across conversations, and autonomously ")
	b.WriteString("improve the project and artifacts (skills, rules, memories) where beneficial.\n\n")

	b.WriteString(fmt.Sprintf("You are operating with IDE context `%s`. ", ide))
	b.WriteString("Use this when interacting with the hub, syncing rules, or any IDE-scoped operations. ")
	b.WriteString(fmt.Sprintf("For example: `%s sync --ide %s` or `%s hub install --ide %s`.\n\n", brand.BinName(), ide, brand.BinName(), ide))

	if subject != nil {
		b.WriteString("## 🎯 Assigned Subject\n\n")
		b.WriteString("**This dream session has a specific subject assigned by the developer.**\n")
		b.WriteString("You MUST prioritize this subject above general exploration.\n\n")
		b.WriteString(fmt.Sprintf("**Subject**: %s\n", subject.Title))
		b.WriteString(fmt.Sprintf("**Instruction file**: `%s`\n\n", subject.Path))
		b.WriteString("### Subject Instructions\n\n")
		b.WriteString("```\n")
		b.WriteString(subject.Body)
		b.WriteString("```\n\n")
		b.WriteString("### Subject Completion Protocol\n\n")
		b.WriteString("When you have completed work on this subject:\n")
		b.WriteString(fmt.Sprintf("1. Create the result file at `%s/%s%s` with a summary of what was done\n",
			SubjectsDir(projectDir), subject.Slug, resultExt))
		b.WriteString("2. Reference this subject in your dream report under **Changes Made** with the tag `[subject]`\n")
		b.WriteString("3. Include a section **Subject Resolution** in your dream report explaining:\n")
		b.WriteString("   - What the developer asked for (the subject)\n")
		b.WriteString("   - What you analyzed and found\n")
		b.WriteString("   - What changes you made to address it\n")
		b.WriteString("   - Whether the subject is fully resolved or partially addressed\n\n")
		b.WriteString("The result file should be a concise markdown summary:\n\n")
		b.WriteString("```markdown\n")
		b.WriteString(fmt.Sprintf("# %s — Result\n\n", subject.Title))
		b.WriteString("## Resolution\n\n")
		b.WriteString("[Explain what was done to address the subject]\n\n")
		b.WriteString("## Changes\n\n")
		b.WriteString("- [List files changed and why]\n\n")
		b.WriteString("## Status\n\n")
		b.WriteString("[COMPLETED | PARTIALLY_COMPLETED — explain what remains]\n")
		b.WriteString("```\n\n")
	}

	b.WriteString("## Your Mission\n\n")

	b.WriteString("### 1. Understand the System\n")
	b.WriteString("- Read the project's knowledge wiki (`" + brand.DotDir() + "/knowledge/project/index.md`)\n")
	b.WriteString("- Query the AST graph to understand code structure\n")
	b.WriteString("- Review **all** project and user memories — these contain deliberate decisions, conventions, and tensions that explain WHY the code is the way it is\n")
	b.WriteString("- Study architectural decisions (ADRs) in `docs/decisions/` — these document trade-offs that were intentionally made\n")
	b.WriteString("- Pay special attention to memories of type `tension` and `decision` — they record explicit choices between alternatives (e.g., \"Chose Postgres over MongoDB because of ACID compliance\")\n")
	b.WriteString("- **Internalize that some code patterns exist for good reasons, even if they look suboptimal at first glance**\n\n")

	b.WriteString("### 2. Review Past Dream Reports\n\n")
	b.WriteString(fmt.Sprintf("Before starting your analysis, read **all** existing dream reports in `%s/dream/`.\n", brand.DotDir()))
	b.WriteString("This includes the report from the current session (if this is a progressive session).\n\n")
	b.WriteString("Pay special attention to the **\"Recommendations for Future\"** section of each report.\n")
	b.WriteString("These are improvements that a previous dream session identified but could not apply.\n")
	b.WriteString("You SHOULD attempt to address these pending recommendations in this session.\n\n")
	b.WriteString("When you fix something that was recommended by a previous dream report:\n")
	b.WriteString("- Reference it explicitly in your Change Log (e.g., \"Addresses recommendation #2 from dream `<id>` \")\n")
	b.WriteString("- Mark it as resolved in your report so the next dream knows it's done\n")
	b.WriteString("- If a recommendation is no longer applicable (code was deleted, requirement changed), note that too\n\n")

	b.WriteString("### 3. Analyze Previous Conversations\n\n")
	b.WriteString("A critical part of your mission is to **mine the developer's conversation history** ")
	b.WriteString("for recurring patterns, unmet needs, and improvement opportunities and create the appropiate skills, commands and memories.\n\n")

	b.WriteString("#### What to Look For\n\n")
	b.WriteString("Read the **most recent 15–20 conversations** and systematically identify:\n\n")
	b.WriteString("1. **Recurring User Requests** — What tasks does the developer repeatedly ask for? ")
	b.WriteString("If the same type of request appears 3+ times (e.g., \"fix X\", \"add logging\", \"refactor pattern Y\"), ")
	b.WriteString("it is a candidate for automation as a **skill**, **command**, or **rule**.\n")
	b.WriteString("2. **User Corrections & Preferences** — When the developer corrects the agent's behavior ")
	b.WriteString("(e.g., \"don't do X\", \"always use Y\", \"prefer Z\"), these reveal conventions that must be memorized.\n")
	b.WriteString("3. **Multi-Step Workflows** — Sequences of actions performed repeatedly across conversations. ")
	b.WriteString("Example: \"create file → update index → run sync → test\". These should become **commands**.\n")
	b.WriteString("4. **Frequently Touched Modules** — Which files/packages does the developer work on most? ")
	b.WriteString("These areas deserve better documentation, more test coverage, and dedicated tooling.\n")
	b.WriteString("5. **Recurring Errors & Problems** — Same error or issue appearing across multiple conversations ")
	b.WriteString("signals a systemic problem needing a root-cause fix, not repeated patches.\n")
	b.WriteString("6. **Undocumented Knowledge** — Domain knowledge, architectural decisions, or technical context ")
	b.WriteString("the developer explains in conversations but is NOT captured in docs, memories, or skills.\n")
	b.WriteString("7. **Abandoned or Incomplete Work** — Conversations where work was started but not finished. ")
	b.WriteString("These may represent important pending tasks worth flagging.\n\n")

	b.WriteString("#### Actions to Take\n\n")
	b.WriteString("| Pattern Found | Action |\n")
	b.WriteString("|---------------|--------|\n")
	b.WriteString("| Same task requested 3+ times | Create a **Skill** or **Command** to automate it |\n")
	b.WriteString("| User correction / \"always do X\" | `graphit memory insert` with type `convention` or `correction` |\n")
	b.WriteString("| Repeated multi-step workflow | Create a **Command** artifact with the full sequence |\n")
	b.WriteString("| Implicit convention not codified | Create a **Rule** artifact to enforce it |\n")
	b.WriteString("| Undocumented decision or context | Create a memory (`decision`) or ADR in `docs/decisions/` |\n")
	b.WriteString("| Recurring error with same root cause | Fix the root cause, document in memory (`skill`) |\n")
	b.WriteString("| Frequently touched but undocumented module | Update `docs/` and create wiki entries |\n")
	b.WriteString("| Abandoned important work | Flag in the dream report under Recommendations for Future |\n\n")

	b.WriteString("### 4. Evaluate Skills & IDE Artifacts\n\n")
	b.WriteString("Review ALL existing IDEs artifacts and evaluate their health, coverage, and coherence.\n\n")

	b.WriteString("#### Skills Analysis\n\n")
	b.WriteString("1. **Overlap Detection** — Do two or more skills cover the same domain? ")
	b.WriteString("If so, **merge** them into a single comprehensive skill. Redundant skills confuse the agent.\n")
	b.WriteString("2. **Scope Creep** — Has a skill grown too broad, covering unrelated concerns? ")
	b.WriteString("If so, **split** it into focused single-purpose skills. Each skill should teach ONE thing well.\n")
	b.WriteString("3. **Staleness** — Is the skill content still accurate? Check file paths, function names, ")
	b.WriteString("API patterns, and conventions it references against the current codebase. Update or delete stale content.\n")
	b.WriteString("4. **Coverage Gaps** — Based on your conversation analysis (step 3), are there recurring ")
	b.WriteString("tasks or patterns with NO corresponding skill? Create new skills for these gaps.\n")
	b.WriteString("5. **Coherence** — Do skills reference each other correctly? Are naming conventions consistent?\n\n")

	b.WriteString("#### Rules & Commands Analysis\n\n")
	b.WriteString("- Are rules still enforced by the codebase? Delete rules for patterns that no longer exist.\n")
	b.WriteString("- Are commands still functional with the current tooling?\n")
	b.WriteString("- Can multiple related rules be consolidated into a single comprehensive rule?\n")
	b.WriteString("- Are there implicit rules (enforced only by convention) that should be explicit?\n\n")

	b.WriteString("#### Artifact Lifecycle Actions\n\n")
	b.WriteString("| Finding | Action |\n")
	b.WriteString("|---------|--------|\n")
	b.WriteString("| Two skills overlap significantly | Merge into one, delete the redundant one |\n")
	b.WriteString("| Skill covers 3+ unrelated topics | Split into focused skills |\n")
	b.WriteString("| Skill references deleted files/APIs | Update content or remove stale skill |\n")
	b.WriteString("| Recurring task has no skill | Create a new skill |\n")
	b.WriteString("| Rule no longer applies | Delete the rule |\n")
	b.WriteString("| Multiple rules overlap | Consolidate into one |\n")
	b.WriteString("| Implicit convention not codified | Create a new rule |\n\n")

	return b.String()
}

func buildDefaultAnalysisRules() string {
	return improvements.Rules()
}

func buildDreamEnvelope(ulid string, subject *Subject) string {
	var b strings.Builder

	b.WriteString("### 10. Document Everything\n\n")
	b.WriteString("Reports you write there are always visible to the developer.\n\n")
	b.WriteString(fmt.Sprintf("Create or update the report at `%s/dream/%s.md`.\n\n", brand.DotDir(), ulid))

	b.WriteString("**CRITICAL: The dream report is the primary deliverable of every session.** ")
	b.WriteString("It must be comprehensive, detailed, and self-contained — a developer reading it ")
	b.WriteString("should fully understand what was analyzed, what was found, what was changed, and why. ")
	b.WriteString("Treat this as a professional audit report, not a summary.\n\n")

	b.WriteString("The report MUST follow this structure:\n\n")

	b.WriteString("```markdown\n")
	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("title: Dream Session %s\n", ulid))
	b.WriteString(fmt.Sprintf("created: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("type: dream-report\n")
	if subject != nil {
		b.WriteString(fmt.Sprintf("subject: %s\n", subject.Slug))
	}
	b.WriteString("---\n\n")

	b.WriteString("# Dream Report\n\n")

	if subject != nil {
		b.WriteString("## Subject Resolution\n\n")
		b.WriteString(fmt.Sprintf("**Subject**: %s\n", subject.Title))
		b.WriteString(fmt.Sprintf("**Slug**: `%s`\n", subject.Slug))
		b.WriteString(fmt.Sprintf("**Instruction file**: `%s`\n\n", subject.Path))
		b.WriteString("### What was requested\n\n")
		b.WriteString("[Summarize what the developer asked for in the subject]\n\n")
		b.WriteString("### Analysis & Findings\n\n")
		b.WriteString("[What you found when investigating the subject — be specific]\n\n")
		b.WriteString("### Actions Taken\n\n")
		b.WriteString("[What changes you made to address the subject — with file paths and diffs]\n\n")
		b.WriteString("### Completion Status\n\n")
		b.WriteString("[COMPLETED | PARTIALLY_COMPLETED — explain what remains if partial]\n\n")
	}

	b.WriteString("## What I Analyzed\n\n")
	b.WriteString("List every module, package, file, or subsystem you examined. Be specific:\n\n")
	b.WriteString("- State the exact files and directories explored (with paths)\n")
	b.WriteString("- Describe which AST queries you ran and what they revealed\n")
	b.WriteString("- Note which wiki pages, memories, or ADRs you consulted\n")
	b.WriteString("- Explain your analysis strategy: what you looked at first and why\n")
	b.WriteString("- Quantify the scope: how many files, functions, LOC reviewed\n\n")

	b.WriteString("## What I Learned\n\n")
	b.WriteString("Describe concrete, specific insights — not generic observations:\n\n")
	b.WriteString("- Architectural patterns and conventions the project follows\n")
	b.WriteString("- How modules interact and where the boundaries are\n")
	b.WriteString("- Technology choices and their implications\n")
	b.WriteString("- Team conventions (naming, error handling, testing patterns)\n")
	b.WriteString("- Strengths of the codebase that should be preserved\n")
	b.WriteString("- Include a PlantUML component or sequence diagram if the architecture is complex:\n\n")
	b.WriteString("```plantuml\n")
	b.WriteString("@startuml\n")
	b.WriteString("' Show the key modules and their relationships\n")
	b.WriteString("' discovered during analysis\n")
	b.WriteString("@enduml\n")
	b.WriteString("```\n\n")

	b.WriteString("## Security Findings\n\n")
	b.WriteString("Even if no issues are found, explicitly state that each category was reviewed.\n")
	b.WriteString("For each finding, provide:\n\n")
	b.WriteString("| # | Severity | Category | File:Line | Description | Resolution |\n")
	b.WriteString("|---|----------|----------|-----------|-------------|------------|\n")
	b.WriteString("| 1 | CRITICAL/HIGH/MEDIUM/LOW | e.g., Data Exposure | path/to/file.go:42 | Exact description | What was done or recommended |\n\n")
	b.WriteString("For each finding, include a **before/after code example**:\n\n")
	b.WriteString("```diff\n")
	b.WriteString("- log.Printf(\"connecting to DB: user=%s pass=%s\", user, password)\n")
	b.WriteString("+ log.Printf(\"connecting to DB: user=%s\", user)  // password redacted\n")
	b.WriteString("```\n\n")
	b.WriteString("If no security issues were found, state: \"All categories reviewed (data exposure, injection, auth, crypto). No issues found.\"\n\n")

	b.WriteString("## Concurrency Findings\n\n")
	b.WriteString("Same format as Security Findings. For each issue:\n\n")
	b.WriteString("| # | Severity | Category | File:Line | Description | Resolution |\n")
	b.WriteString("|---|----------|----------|-----------|-------------|------------|\n\n")
	b.WriteString("Include before/after code examples showing the fix:\n\n")
	b.WriteString("```diff\n")
	b.WriteString("- // Unprotected map access from multiple goroutines\n")
	b.WriteString("- cache[key] = value\n")
	b.WriteString("+ mu.Lock()\n")
	b.WriteString("+ cache[key] = value\n")
	b.WriteString("+ mu.Unlock()\n")
	b.WriteString("```\n\n")
	b.WriteString("If no issues found: \"All categories reviewed (race conditions, idempotency, resource leaks). No issues found.\"\n\n")

	b.WriteString("## Twelve-Factor App Findings\n\n")
	b.WriteString("Evaluate each relevant factor. Use a checklist format:\n\n")
	b.WriteString("| Factor | Status | Details |\n")
	b.WriteString("|--------|--------|---------|\n")
	b.WriteString("| III. Config | ⚠️ VIOLATION | Hardcoded DB URL in `config/db.go:15` |\n")
	b.WriteString("| VI. Processes | ✅ PASS | No local state found between requests |\n")
	b.WriteString("| XI. Logs | ⚠️ VIOLATION | Log files written to `/var/log/` in `logger.go:30` |\n\n")
	b.WriteString("For violations, include the specific fix applied or recommended.\n\n")

	b.WriteString("## Observability Findings (MELT)\n\n")
	b.WriteString("Evaluate each dimension. Use a checklist format:\n\n")
	b.WriteString("| Dimension | Status | Details |\n")
	b.WriteString("|-----------|--------|---------|\n")
	b.WriteString("| Metrics | ⚠️ GAP | Payment handler has no latency/error metrics |\n")
	b.WriteString("| Events | ⚠️ GAP | Deploy events not emitted; no timeline correlation |\n")
	b.WriteString("| Logs | ✅ PASS | Structured JSON logging with correlation IDs |\n")
	b.WriteString("| Traces | ⚠️ GAP | Outbound HTTP calls don't propagate trace context |\n")
	b.WriteString("| Context Propagation | ⚠️ GAP | Background workers lose request context |\n")
	b.WriteString("| OTel Standardization | ⚠️ GAP | Using vendor-specific Datadog SDK instead of OTel |\n\n")
	b.WriteString("For each gap, describe the specific issue and the fix applied or recommended.\n")
	b.WriteString("If no issues found: \"All dimensions reviewed (metrics, events, logs, traces, context propagation, OTel). No gaps found.\"\n\n")

	b.WriteString("## Clean Code Improvements\n\n")
	b.WriteString("Group findings by principle. For each:\n\n")
	b.WriteString("### DRY Violations\n")
	b.WriteString("- Describe the duplicated pattern, where it appeared (file:line), and how it was consolidated\n")
	b.WriteString("- Show before/after code diff\n\n")
	b.WriteString("### YAGNI Removals\n")
	b.WriteString("- List dead code, unused abstractions, or over-engineered structures removed\n")
	b.WriteString("- Justify why the code was unnecessary\n\n")
	b.WriteString("### KISS Simplifications\n")
	b.WriteString("- Show the complex pattern and the simpler replacement\n")
	b.WriteString("- Explain why the simpler version is correct and safe\n\n")
	b.WriteString("### Naming & Readability\n")
	b.WriteString("- List renamed variables, functions, or types with before → after\n")
	b.WriteString("- Explain how the new name better communicates intent\n\n")
	b.WriteString("### Error Handling\n")
	b.WriteString("- Show errors that were silently swallowed or lacked context\n")
	b.WriteString("- Show the improved error handling with diff\n\n")

	b.WriteString("## Changes Made\n\n")
	b.WriteString("**This is the most critical section.** Every change must be individually documented:\n\n")
	b.WriteString("### Change Log\n\n")
	b.WriteString("| # | File | Type | Principle | Summary |\n")
	b.WriteString("|---|------|------|-----------|--------|\n")
	b.WriteString("| 1 | `path/to/file.go` | refactor | DRY | Extracted duplicated validation into `validateInput()` |\n")
	b.WriteString("| 2 | `path/to/handler.go` | security | Data Exposure | Removed password from error log |\n")
	b.WriteString("| 3 | `path/to/worker.go` | concurrency | Idempotency | Added deduplication key to job processor |\n\n")
	b.WriteString("### Detailed Change Descriptions\n\n")
	b.WriteString("For each change in the table above, provide:\n\n")
	b.WriteString("#### Change #N: [title]\n")
	b.WriteString("- **File(s)**: exact paths modified\n")
	b.WriteString("- **Principle**: which principle motivated this (DRY, KISS, Security, etc.)\n")
	b.WriteString("- **Problem**: what was wrong — with code example\n")
	b.WriteString("- **Solution**: what was done — with code diff\n")
	b.WriteString("- **Risk**: LOW/MEDIUM/HIGH — why this change is safe\n")
	b.WriteString("- **Testing**: how the change can be verified\n\n")

	b.WriteString("## Architectural Impact\n\n")
	b.WriteString("If any changes affected module boundaries, dependencies, or data flow, include a ")
	b.WriteString("PlantUML diagram showing the before and after state:\n\n")
	b.WriteString("```plantuml\n")
	b.WriteString("@startuml\n")
	b.WriteString("title Changes Impact — Before vs After\n")
	b.WriteString("' Left side: before\n")
	b.WriteString("' Right side: after\n")
	b.WriteString("' Highlight what changed\n")
	b.WriteString("@enduml\n")
	b.WriteString("```\n\n")
	b.WriteString("Assess overall impact:\n")
	b.WriteString("- **Backward compatibility**: Are all changes backward-compatible? Any breaking changes?\n")
	b.WriteString("- **Risk level**: Overall risk of this session's changes (LOW/MEDIUM/HIGH)\n")
	b.WriteString("- **Test coverage**: Were new tests added? Existing tests still pass?\n")
	b.WriteString("- **Dependencies affected**: Did any module API surface change?\n\n")

	b.WriteString("## Recommendations for Future\n\n")
	b.WriteString("List improvements that were **identified but NOT applied** because they:\n")
	b.WriteString("- Require human judgment or domain knowledge\n")
	b.WriteString("- Would be breaking changes needing migration planning\n")
	b.WriteString("- Are too large for a single dream session\n")
	b.WriteString("- Touch security-sensitive areas that need explicit review\n\n")
	b.WriteString("For each recommendation, provide a numbered entry:\n\n")
	b.WriteString("### Recommendation #N: [title]\n")
	b.WriteString("- **Location**: file:line\n")
	b.WriteString("- **Severity**: LOW/MEDIUM/HIGH/CRITICAL\n")
	b.WriteString("- **Category**: Security / Concurrency / Clean Code / 12-Factor / Architecture\n")
	b.WriteString("- **Problem**: what is wrong and why it matters\n")
	b.WriteString("- **Proposed solution**: what should be done\n")
	b.WriteString("- **Risks**: what could go wrong with the proposed solution\n")
	b.WriteString("- **Effort**: SMALL / MEDIUM / LARGE\n\n")
	b.WriteString("These recommendations will be reviewed by the next dream session. Be specific enough\n")
	b.WriteString("that a future agent can act on them without re-analyzing the entire system.\n\n")

	b.WriteString("## Addressed Recommendations from Previous Dreams\n\n")
	b.WriteString("If you addressed any recommendations from previous dream reports, list them here:\n\n")
	b.WriteString("| Source Dream | Recommendation # | Title | Status |\n")
	b.WriteString("|-------------|-----------------|-------|--------|\n")
	b.WriteString("| `<dream-id>` | #N | [title] | ✅ Resolved / ⚠️ Partially resolved / ❌ No longer applicable |\n\n")
	b.WriteString("For each addressed recommendation, briefly explain what was done and reference the\n")
	b.WriteString("corresponding entry in the Changes Made section above.\n\n")
	b.WriteString("If no previous dreams exist or no recommendations were pending, state: \"No prior recommendations to address.\"\n\n")

	b.WriteString("## Conversation Analysis Findings\n\n")
	b.WriteString("Document what you discovered by analyzing the developer's conversation history:\n\n")
	b.WriteString("### Recurring Patterns Identified\n\n")
	b.WriteString("| # | Pattern | Frequency | Conversations | Action Taken |\n")
	b.WriteString("|---|---------|-----------|---------------|--------------|\n")
	b.WriteString("| 1 | e.g., \"User frequently asks for X\" | 5 times | `<id1>`, `<id2>`, ... | Created skill / memory / rule |\n\n")
	b.WriteString("### Memories Created from Conversations\n\n")
	b.WriteString("List each memory created or updated based on conversation analysis:\n")
	b.WriteString("- `graphit memory insert \"<title>\"` — reason: <why this was worth memorizing>\n\n")
	b.WriteString("### Artifacts Created or Modified\n\n")
	b.WriteString("List each skill, rule, or command created/modified based on conversation patterns:\n")
	b.WriteString("- [<type>] `<name>` — <description of what it automates/enforces>\n\n")
	b.WriteString("If no conversations were analyzed (e.g., no logs found), state: \"No conversation logs available.\"\n\n")

	b.WriteString("## Artifact Health Report\n\n")
	b.WriteString("Document the evaluation of existing IDE artifacts:\n\n")
	b.WriteString("### Skills Evaluated\n\n")
	b.WriteString("| Skill | Status | Action | Details |\n")
	b.WriteString("|-------|--------|--------|---------|\n")
	b.WriteString("| `<skill-name>` | ✅ Healthy / ⚠️ Stale / 🔀 Merged / ✂️ Split / ❌ Deleted | <what was done> | <reasoning> |\n\n")
	b.WriteString("### Rules & Commands Evaluated\n\n")
	b.WriteString("| Artifact | Type | Status | Action |\n")
	b.WriteString("|----------|------|--------|--------|\n")
	b.WriteString("| `<name>` | rule/command | ✅/⚠️/❌ | <what was done> |\n\n")
	b.WriteString("### Coverage Gaps Identified\n\n")
	b.WriteString("List recurring needs with no corresponding artifact:\n")
	b.WriteString("- <gap description> → Created [<type>] `<name>`\n\n")
	b.WriteString("If no artifacts exist yet, state: \"No existing artifacts found. Created N new artifacts based on analysis.\"\n")

	b.WriteString("```\n\n")

	b.WriteString("### 11. Commit Your Code Changes\n\n")
	b.WriteString(fmt.Sprintf("You are working on branch `dream/%s`. ", ulid))
	b.WriteString("Commit CODE changes (improvements, refactors) to this branch.\n")
	b.WriteString(fmt.Sprintf("The dream report at `%s/dream/%s.md` lives in the project directory ", brand.DotDir(), ulid))
	b.WriteString("and does NOT need to be committed — it persists automatically.\n\n")

	b.WriteString("### 12. Deep Sleep — Signal When Done\n\n")
	b.WriteString("After completing your analysis, you MUST decide whether there are further improvements to make.\n\n")
	b.WriteString("**If you found NOTHING to improve** (the codebase is in good shape, or you have already ")
	b.WriteString("exhausted all improvements in previous progressive sessions), signal **deep sleep** by creating:\n\n")
	b.WriteString(fmt.Sprintf("```bash\ntouch %s/dream/%s%s\n```\n\n", brand.DotDir(), ulid, DeepSleepSentinelName()))
	b.WriteString("This tells the daemon that this dream cycle is complete. No more sessions will run until ")
	b.WriteString("the developer makes new changes to the project and a new cycle begins.\n\n")
	b.WriteString("**If you DID make improvements**, do NOT create this file — the daemon will schedule ")
	b.WriteString("another session to continue progressive work.\n\n")

	b.WriteString("## Rules\n\n")
	b.WriteString("- Do NOT merge into main or any other branch\n")
	b.WriteString("- Do NOT push to remote\n")
	b.WriteString("- Do NOT delete or modify test fixtures\n")
	b.WriteString("- Do NOT change CI/CD configuration\n")
	b.WriteString("- Do NOT modify security-sensitive files (credentials, vault configs, .env files)\n")
	b.WriteString("- ALWAYS preserve existing behavior — refactor, don't rewrite\n")
	b.WriteString("- PREFER documentation and test improvements when uncertain about a code change\n")
	b.WriteString("- PRIORITIZE security fixes over style improvements\n")
	b.WriteString("- NEVER introduce new dependencies without strong justification\n")
	b.WriteString(fmt.Sprintf("- ALWAYS create `%s/dream/%s%s` if you found nothing to improve\n",
		brand.DotDir(), ulid, DeepSleepSentinelName()))
	b.WriteString(fmt.Sprintf("- NEVER create `%s/dream/%s%s` if you made any changes\n",
		brand.DotDir(), ulid, DeepSleepSentinelName()))

	return b.String()
}

func buildDreamArtifact(ulid, agentOutput string) string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("title: Dream Session %s\n", ulid))
	b.WriteString(fmt.Sprintf("created: %s\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("type: dream-report\n")
	b.WriteString("---\n\n")

	b.WriteString("# Dream Report\n\n")
	b.WriteString(fmt.Sprintf("**Dream ID**: `%s`\n", ulid))
	b.WriteString(fmt.Sprintf("**Timestamp**: `%s`\n\n", time.Now().UTC().Format(time.RFC3339)))

	b.WriteString("## Agent Output\n\n")
	b.WriteString(agentOutput)
	b.WriteString("\n")

	return b.String()
}
